import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-bastide-key","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}});
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function player(req:Request){const key=req.headers.get("x-bastide-key")||"";if(!key)return null;const token_hash=await hash(key);const {data}=await db.from("bastide_players").select("id,display_name,state").eq("token_hash",token_hash).maybeSingle();return data}
async function admin(req:Request){const key=req.headers.get("x-bastide-key")||"";if(!key)return false;const token_hash=await hash(key);const {data}=await db.from("bastide_admin_tokens").select("token_hash").eq("token_hash",token_hash).is("revoked_at",null).maybeSingle();return !!data}
Deno.serve(async req=>{try{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const url=new URL(req.url),action=url.searchParams.get("action")||"state";
  if(action==="catalog"&&req.method==="GET"){const {data,error}=await db.from("bastide_shop_items").select("*").eq("active",true).order("sort_order");if(error)throw error;return json({items:data})}
  if(action==="state"&&req.method==="GET"){const p=await player(req);return p?json({player:p}):json({error:"Lien joueur requis"},401)}
  if(action==="state"&&req.method==="PUT"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const body=await req.json();const state={silver:Math.max(0,Number(body.state?.silver)||0),inventory:Array.isArray(body.state?.inventory)?body.state.inventory.slice(0,250):[]};const {data,error}=await db.from("bastide_players").update({state,updated_at:new Date().toISOString()}).eq("id",p.id).select("state").single();if(error)throw error;return json(data)}
  if(action==="bootstrap"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);if((p.state?.inventory||[]).length)return json({state:p.state,kept:true});const body=await req.json();const state={silver:Math.max(0,Number(body.state?.silver)||0),inventory:Array.isArray(body.state?.inventory)?body.state.inventory.slice(0,250):[]};const {error}=await db.from("bastide_players").update({state,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)throw error;return json({state})}
  if(action==="purchase"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const body=await req.json();const {data,error}=await db.rpc("bastide_purchase",{p_player_id:p.id,p_item_id:body.itemId,p_quantity:Number(body.quantity)||1});if(error)return json({error:error.message},400);return json({state:data})}
  if(action==="admin"&&req.method==="GET"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const [{data:players,error:e1},{data:items,error:e2},{data:events,error:e3}]=await Promise.all([db.from("bastide_players").select("id,display_name,state,updated_at").order("display_name"),db.from("bastide_shop_items").select("*").order("sort_order"),db.from("bastide_inventory_events").select("*").order("created_at",{ascending:false}).limit(50)]);if(e1||e2||e3)throw(e1||e2||e3);return json({players,items,events})}
  if(action==="send"&&req.method==="POST"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const body=await req.json(),ids=Array.isArray(body.playerIds)?body.playerIds:[];if(!ids.length)return json({error:"Aucun destinataire"},400);for(const id of ids){const {data:p,error}=await db.from("bastide_players").select("state").eq("id",id).single();if(error)throw error;const state=p.state||{silver:0,inventory:[]};if(body.item)state.inventory=[...(state.inventory||[]),{id:"mj-"+crypto.randomUUID(),name:String(body.item.name||"Objet du MJ"),base:String(body.item.base||""),category:String(body.item.category||"Équipement"),quantity:Math.max(1,Number(body.item.quantity)||1),equipped:false,chargesMax:Math.max(0,Number(body.item.chargesMax)||0),charges:Math.max(0,Number(body.item.chargesMax)||0),notes:String(body.item.notes||"")}];state.silver=Math.max(0,Number(state.silver)||0)+Math.max(0,Number(body.silver)||0);await db.from("bastide_players").update({state,updated_at:new Date().toISOString()}).eq("id",id);await db.from("bastide_inventory_events").insert({player_id:id,event_type:"mj_send",summary:body.item?`Objet reçu : ${body.item.name}`:`Monnaie reçue : ${body.silver} pa`,details:{item:body.item||null,silver:Number(body.silver)||0}})}return json({ok:true,count:ids.length})}
  if(action==="shop-item"&&req.method==="POST"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json(),row={name:String(b.name||"").trim(),base:String(b.base||""),category:String(b.category||"Équipement"),description:String(b.description||""),price_silver:Math.max(0,Number(b.price_silver)||0),stock:b.stock===""||b.stock==null?null:Math.max(0,Number(b.stock)||0),active:b.active!==false,sort_order:Number(b.sort_order)||100};if(!row.name)return json({error:"Nom requis"},400);const q=b.id?db.from("bastide_shop_items").update(row).eq("id",b.id):db.from("bastide_shop_items").insert(row);const {error}=await q;if(error)throw error;return json({ok:true})}
  return json({error:"Action inconnue"},404)
}catch(error){console.error(error);return json({error:error instanceof Error?error.message:"Erreur serveur"},500)}});
