import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type,x-bastide-key","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function player(req:Request){const key=req.headers.get("x-bastide-key")||"";if(!key)return null;const token_hash=await hash(key);const{data}=await db.from("bastide_players").select("id,display_name,state,updated_at").eq("token_hash",token_hash).maybeSingle();return data}
async function admin(req:Request){const key=req.headers.get("x-bastide-key")||"";if(!key)return false;const token_hash=await hash(key);const{data}=await db.from("bastide_admin_tokens").select("token_hash").eq("token_hash",token_hash).is("revoked_at",null).maybeSingle();return!!data}
const cleanEquipment=(value:any)=>{if(!value||typeof value!=="object"||Array.isArray(value))return{};const slot=["main_hand","off_hand","armor","shield","feet","accessory_1","accessory_2"].includes(String(value.slot))?String(value.slot):"";const bonuses=value.bonuses&&typeof value.bonuses==="object"&&!Array.isArray(value.bonuses)?Object.fromEntries(Object.entries(value.bonuses).filter(([k,v])=>["armorDef","shieldDef","def","initiative","contact","distance","magic"].includes(k)&&Number.isFinite(Number(v))).map(([k,v])=>[k,Number(v)])):{};const equipment:any={};if(slot)equipment.slot=slot;if(value.effect)equipment.effect=String(value.effect).slice(0,500);if(Object.keys(bonuses).length)equipment.bonuses=bonuses;if(value.weapon&&typeof value.weapon==="object")equipment.weapon=value.weapon;return equipment};
const cleanItem=(x:any)=>({id:String(x?.id||("item-"+crypto.randomUUID())),name:String(x?.name||"Objet").slice(0,120),base:String(x?.base||"").slice(0,120),category:String(x?.category||"Équipement").slice(0,60),quantity:Math.max(0,Number(x?.quantity)||0),equipped:!!x?.equipped,chargesMax:Math.max(0,Number(x?.chargesMax)||0),charges:Math.max(0,Number(x?.charges)||0),notes:String(x?.notes||"").slice(0,3000),mediaUrl:String(x?.mediaUrl||"").slice(0,1000),mediaType:String(x?.mediaType||"").slice(0,30),source:String(x?.source||"joueur").slice(0,40),receivedAt:String(x?.receivedAt||""),equipment:cleanEquipment(x?.equipment)});
Deno.serve(async req=>{try{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  const url=new URL(req.url),action=url.searchParams.get("action")||"state";
  if(action==="catalog"&&req.method==="GET"){const{data,error}=await db.from("bastide_shop_items").select("*").eq("active",true).order("sort_order");if(error)throw error;return json({items:data})}
  if(action==="maps"&&req.method==="GET"){const{data,error}=await db.from("bastide_maps").select("id,title,description,image_url,sort_order").eq("player_visible",true).order("sort_order");if(error)throw error;return json({maps:data||[]})}
  if(action==="state"&&req.method==="GET"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const[{data:events,error},{data:recipients,error:recipientsError}]=await Promise.all([db.from("bastide_inventory_events").select("id,event_type,summary,details,created_at,seen_at").eq("player_id",p.id).order("created_at",{ascending:false}).limit(30),db.from("bastide_players").select("id,display_name").neq("id",p.id).order("display_name")]);if(error||recipientsError)throw(error||recipientsError);return json({player:p,recipients:recipients||[],events:events||[],unseen:(events||[]).filter((e:any)=>!e.seen_at).length})}
  if(action==="bootstrap"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);if((p.state?.inventory||[]).length)return json({state:p.state,kept:true});const b=await req.json(),money=b.state?.money||{po:0,pa:Math.max(0,Number(b.state?.silver)||0),pc:0};const state={silver:Math.max(0,Number(money.pa)||0),money:{po:Math.max(0,Number(money.po)||0),pa:Math.max(0,Number(money.pa)||0),pc:Math.max(0,Number(money.pc)||0)},inventory:Array.isArray(b.state?.inventory)?b.state.inventory.slice(0,250).map(cleanItem):[]};const{error}=await db.from("bastide_players").update({state,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)throw error;return json({state})}
  if(action==="item"&&["POST","PATCH","DELETE"].includes(req.method)){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const b=await req.json(),op=req.method==="DELETE"?"delete":(req.method==="POST"?"create":"upsert"),item=cleanItem(b.item);const{data,error}=await db.rpc("bastide_item_mutation",{p_player_id:p.id,p_action:op,p_item:item});if(error)throw error;return json({state:data})}
  if(action==="money"&&req.method==="POST")return json({error:"La monnaie est administrée par le MJ"},403);
  if(action==="transfer-money"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const b=await req.json(),recipientId=String(b.recipientId||""),amount={po:Math.max(0,Number(b.amount?.po)||0),pa:Math.max(0,Number(b.amount?.pa)||0),pc:Math.max(0,Number(b.amount?.pc)||0)};if(!recipientId)return json({error:"Destinataire requis"},400);const{data,error}=await db.rpc("bastide_transfer_money",{p_sender_id:p.id,p_recipient_id:recipientId,p_amount:amount});if(error)return json({error:error.message},400);return json({state:data})}
  if(action==="transfer-item"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const b=await req.json(),recipientId=String(b.recipientId||""),itemId=String(b.itemId||""),quantity=Math.max(0,Math.floor(Number(b.quantity)||0));if(!recipientId||!itemId||quantity<1)return json({error:"Objet, destinataire et quantité requis"},400);const{data,error}=await db.rpc("bastide_transfer_item",{p_sender_id:p.id,p_recipient_id:recipientId,p_item_id:itemId,p_quantity:quantity});if(error)return json({error:error.message},400);return json({state:data})}
  if(action==="seen"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const{data,error}=await db.rpc("bastide_mark_events_seen",{p_player_id:p.id});if(error)throw error;return json({ok:true,count:data})}
  if(action==="purchase"&&req.method==="POST"){const p=await player(req);if(!p)return json({error:"Lien joueur requis"},401);const b=await req.json();const{data,error}=await db.rpc("bastide_purchase",{p_player_id:p.id,p_item_id:b.itemId,p_quantity:Number(b.quantity)||1});if(error)return json({error:error.message},400);return json({state:data})}
  if(action==="admin"&&req.method==="GET"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const[{data:players,error:e1},{data:items,error:e2},{data:events,error:e3},{data:scenario,error:e4},{data:maps,error:e5}]=await Promise.all([db.from("bastide_players").select("id,display_name,state,updated_at").order("display_name"),db.from("bastide_shop_items").select("*").order("sort_order"),db.from("bastide_inventory_events").select("*").order("created_at",{ascending:false}).limit(100),db.from("bastide_scenario_items").select("*").eq("active",true).order("sort_order"),db.from("bastide_maps").select("*").order("sort_order")]);if(e1||e2||e3||e4||e5)throw(e1||e2||e3||e4||e5);return json({players,items,events,scenario,maps})}
  if(action==="send"&&req.method==="POST"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json(),playerId=String(b.playerId||""),items=Array.isArray(b.items)?b.items.slice(0,30).map(cleanItem):[],money={po:Math.max(0,Number(b.money?.po)||0),pa:Math.max(0,Number(b.money?.pa)||0),pc:Math.max(0,Number(b.money?.pc)||0)};if(!playerId)return json({error:"Destinataire requis"},400);if(!items.length&&!money.po&&!money.pa&&!money.pc)return json({error:"Envoi vide"},400);const summary=String(b.summary||"Envoi du MJ").slice(0,200);const{data,error}=await db.rpc("bastide_deliver_bundle",{p_player_id:playerId,p_items:items,p_money:money,p_summary:summary});if(error)throw error;return json({ok:true,...data})}
  if(action==="shop-item"&&["POST","PATCH"].includes(req.method)){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json(),row={name:String(b.name||"").trim(),base:String(b.base||""),category:String(b.category||"Équipement"),description:String(b.description||""),price_silver:Math.max(0,Number(b.price_silver)||0),stock:b.stock===""||b.stock==null?null:Math.max(0,Number(b.stock)||0),charges_max:Math.max(0,Number(b.charges_max)||0),equipment:cleanEquipment(b.equipment),active:b.active!==false,sort_order:Number(b.sort_order)||100};if(!row.name)return json({error:"Nom requis"},400);const q=b.id?db.from("bastide_shop_items").update({...row,updated_at:new Date().toISOString()}).eq("id",b.id):db.from("bastide_shop_items").insert(row);const{error}=await q;if(error)throw error;return json({ok:true})}
  if(action==="shop-item"&&req.method==="DELETE"){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json();const{error}=await db.from("bastide_shop_items").update({active:false,updated_at:new Date().toISOString()}).eq("id",b.id);if(error)throw error;return json({ok:true})}
  if(action==="scenario-item"&&["POST","PATCH"].includes(req.method)){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json(),row={id:String(b.id||("scenario-"+crypto.randomUUID())),title:String(b.title||"").trim(),kind:String(b.kind||"object"),category:String(b.category||"Objet de quête"),description:String(b.description||""),image_url:String(b.image_url||""),mechanical_base:String(b.mechanical_base||""),equipment:cleanEquipment(b.equipment),active:b.active!==false,sort_order:Number(b.sort_order)||100,updated_at:new Date().toISOString()};if(!row.title)return json({error:"Titre requis"},400);const{error}=await db.from("bastide_scenario_items").upsert(row);if(error)throw error;return json({ok:true})}
  if(action==="map-item"&&["POST","PATCH"].includes(req.method)){if(!await admin(req))return json({error:"Accès MJ requis"},401);const b=await req.json(),row={id:String(b.id||("map-"+crypto.randomUUID())),title:String(b.title||"").trim(),description:String(b.description||""),image_url:String(b.image_url||"").trim(),player_visible:!!b.player_visible,sort_order:Number(b.sort_order)||100,updated_at:new Date().toISOString()};if(!row.title||!row.image_url)return json({error:"Titre et image requis"},400);const{error}=await db.from("bastide_maps").upsert(row);if(error)throw error;return json({ok:true})}
  return json({error:"Action inconnue"},404);
}catch(error){console.error(error);return json({error:error instanceof Error?error.message:"Erreur serveur"},500)}});
