"use strict";
var supa=null,syncTimer=null,syncChannel=null,syncApplying=false,currentUser=null;
function syncAvailable(){return !!(SYNC_CONFIG.url&&SYNC_CONFIG.publishableKey&&window.supabase)}
function initSync(){if(!syncAvailable())return;try{supa=window.supabase.createClient(SYNC_CONFIG.url,SYNC_CONFIG.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});supa.auth.onAuthStateChange(function(evt,session){currentUser=session&&session.user?session.user:null;if(currentUser)connectRemote();else disconnectRemote();renderSync()});supa.auth.getSession().then(function(r){currentUser=r.data&&r.data.session?r.data.session.user:null;if(currentUser)connectRemote();renderSync()})}catch(e){supa=null}}
function scheduleSync(){if(!supa||!currentUser||syncApplying)return;clearTimeout(syncTimer);syncTimer=setTimeout(pushState,650)}
async function pushState(){if(!supa||!currentUser)return;try{var now=new Date().toISOString();var r=await supa.from("budget_states").upsert({user_id:currentUser.id,payload:state,updated_at:now},{onConflict:"user_id"});if(r.error)throw r.error;state.lastSyncAt=now;localStorage.setItem(KEY,JSON.stringify(state));renderSync()}catch(e){$("syncStateText").textContent="Erreur de synchronisation : "+e.message}}
async function connectRemote(){if(!supa||!currentUser)return;try{var r=await supa.from("budget_states").select("payload,updated_at").eq("user_id",currentUser.id).maybeSingle();if(r.error)throw r.error;if(r.data&&r.data.payload){syncApplying=true;var localAccount=state&&state.currentAccountId?state.currentAccountId:"lcl";state=ensureMultiAccount(r.data.payload);if(state.currentAccounts&&state.currentAccounts[localAccount])applyActiveAccount(state,localAccount);state.lastSyncAt=r.data.updated_at||state.lastSyncAt;localStorage.setItem(KEY,JSON.stringify(state));syncApplying=false;render()}else await pushState();if(syncChannel)await supa.removeChannel(syncChannel);syncChannel=supa.channel("budget-state-"+currentUser.id).on("postgres_changes",{event:"*",schema:"public",table:"budget_states",filter:"user_id=eq."+currentUser.id},function(payload){var row=payload.new;if(!row||!row.payload)return;syncApplying=true;var localAccount=state&&state.currentAccountId?state.currentAccountId:"lcl";state=ensureMultiAccount(row.payload);if(state.currentAccounts&&state.currentAccounts[localAccount])applyActiveAccount(state,localAccount);state.lastSyncAt=row.updated_at||new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));syncApplying=false;render()}).subscribe()}catch(e){$("syncStateText").textContent="Connexion à la base impossible : "+e.message}}
async function disconnectRemote(){if(supa&&syncChannel){try{await supa.removeChannel(syncChannel)}catch(e){}syncChannel=null}currentUser=null;renderSync()}
function renderSync(){var ready=!!supa,logged=!!currentUser;$("syncDot").classList.toggle("ok",logged);$("syncLabel").textContent=logged?"Synchronisé":(ready?"Prêt à connecter":"Mode local");$("syncStateTitle").textContent=logged?"Synchronisation active":(ready?"Base privée prête":"Pas encore connectée");$("syncStateText").textContent=logged?("Connecté : "+currentUser.email+". Les deux téléphones utilisant ce compte partagent les mêmes données."):(ready?"Connectez le même compte foyer sur vos deux téléphones.":"Le code est prêt pour une base privée dédiée. Tant que le projet Supabase n'est pas créé, vos données restent sur ce téléphone.");$("authBtn").disabled=!ready;$("authBtn").textContent=logged?"Gérer la connexion":"Connexion au foyer"}
function openAuth(){if(!supa)return;$("authEmail").value=currentUser&&currentUser.email?currentUser.email:"";$("authPassword").value="";$("authMessage").textContent=currentUser?"Compte actuellement connecté.":"";$("signOutBtn").classList.toggle("hidden",!currentUser);$("signInBtn").disabled=!!currentUser;$("signUpBtn").disabled=!!currentUser;$("authDialog").showModal()}
async function authAction(kind){var email=$("authEmail").value.trim(),password=$("authPassword").value;if(!email||password.length<8){$("authMessage").textContent="Renseigne un email et un mot de passe d'au moins 8 caractères.";return}$("authMessage").textContent="Connexion…";try{var r=kind==="signup"?await supa.auth.signUp({email:email,password:password,options:{emailRedirectTo:location.href.split("#")[0]}}):await supa.auth.signInWithPassword({email:email,password:password});if(r.error)throw r.error;$("authMessage").textContent=kind==="signup"&&!r.data.session?"Compte créé. Vérifie l'email de confirmation, puis connecte-toi.":"Connecté. La synchronisation démarre."}catch(e){$("authMessage").textContent="Erreur : "+e.message}}
