(function(){
'use strict';
const D=window.BASTIDE_CHARACTER;
if(!D){document.body.innerHTML='<p>Fiche de personnage indisponible.</p>';return}
const id=D.id||'hero',key='iot_bastide_cof2_'+id+'_v2',oldKey='iot_bastide_cof2_'+id+'_v1';
const max={hp:Number(D.combat?.pvMax)||0,pc:Number(D.combat?.pcMax)||0,pm:Number(D.combat?.pmMax)||0,dr:Number(D.combat?.recoveryMax)||0};
const defaults={hp:max.hp,pc:max.pc,pm:max.pm,dr:max.dr,silver:Number(D.combat?.silver)||0,player:'',ideal:D.heroicIdeal||'',flaw:D.flaw||'',notes:'',conditions:[],uses:{},ammo:{}};
let S=load();
function load(){let value=null;try{value=JSON.parse(localStorage.getItem(key)||'null')}catch(_e){}if(!value){try{value=JSON.parse(localStorage.getItem(oldKey)||'null')}catch(_e){}}return Object.assign({},defaults,value||{})}
function save(){localStorage.setItem(key,JSON.stringify(S))}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function signed(n){n=Number(n)||0;return(n>=0?'+':'')+n}
function slug(value){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function clamp(n,min,maxi){return Math.max(min,Math.min(maxi,Number(n)||0))}
function ownedAbilities(){return(D.paths||[]).flatMap(path=>(path.ranks||[]).filter(rank=>rank.owned).map(rank=>Object.assign({path:path.name,id:slug(path.name+'-'+rank.rank+'-'+rank.name)},rank)))}
function actionType(a){const name=(a.name||'').toUpperCase();const text=(a.text||'').toLowerCase();if(/\(L\)/.test(name)||/action limitée/.test(text))return'L';if(/\(A\)/.test(name)||/action d.attaque/.test(text))return'A';if(/\(M\)/.test(name)||/action de mouvement/.test(text))return'M';if(/\(G\)/.test(name)||/action gratuite/.test(text))return'G';return'Passif'}
function usage(a){const text=((a.name||'')+' '+(a.text||'')).toLowerCase();if(/une fois par (jour|journée) par rang/.test(text))return{scope:'day',max:Number(a.rank)||1,label:(Number(a.rank)||1)+' fois/jour'};if(/une fois par (jour|journée)|1 fois par (jour|journée)/.test(text))return{scope:'day',max:1,label:'1 fois/jour'};if(/une fois par combat|1 fois par combat/.test(text))return{scope:'combat',max:1,label:'1 fois/combat'};const m=text.match(/(\d+) fois par (jour|journée|combat)/);if(m)return{scope:m[2]==='combat'?'combat':'day',max:Number(m[1]),label:m[1]+' fois/'+(m[2]==='combat'?'combat':'jour')};return null}
function resourceCost(a){const text=(a.text||'');const pm=text.match(/(?:pour|coûte|dépense|dépenser)\s+(\d+)\s*PM/i);const pc=text.match(/(?:pour|coûte|dépense|dépenser)\s+(\d+)\s*PC/i);const dr=text.match(/(?:pour|coûte|dépense|dépenser)\s+(\d+)\s*DR/i);if(pm)return{kind:'pm',amount:+pm[1],label:pm[1]+' PM'};if(pc)return{kind:'pc',amount:+pc[1],label:pc[1]+' PC'};if(dr)return{kind:'dr',amount:+dr[1],label:dr[1]+' DR'};if(/\*/.test(a.name||''))return{kind:'pm',amount:Number(a.rank)||1,label:(Number(a.rank)||1)+' PM (rang du sort)'};return null}
const conditionsInfo={Affaibli:'Dé malus aux tests utilisant FOR, AGI ou CON.',Aveuglé:'-5 en attaque au contact et en DEF ; -10 pour attaquer à distance.',Étourdi:'Aucune action et -5 en DEF.',Immobilisé:'Aucun déplacement et dé malus en attaque.',Ralenti:'Une seule action de mouvement ou d’attaque.',Renversé:'-5 en DEF ; une action d’attaque est nécessaire pour se relever.',Surpris:'Ne peut pas agir avant son premier tour et vulnérable à certains effets.',Inconscient:'Ne peut pas agir. La situation exacte est tranchée par le MJ.'};
document.body.innerHTML=`<main class="sheet"><header class="sheet-top"><a class="back" href="../../joueurs/">← Espace joueurs</a><span class="pill">COF2 · fiche interactive</span></header><div class="tabs-wrap"><nav class="tabs" aria-label="Sections"><button class="active" data-page="play">Jouer</button><button data-page="fight">Combat</button><button data-page="abilities">Capacités</button><button data-page="stats">Caracs</button><button data-page="bag">Inventaire</button><button data-page="rest">Suivi</button><button data-page="notes">Notes</button></nav></div><article class="paper"><header class="identity"><div><small>PERSONNAGE DE LA BASTIDE</small><h1>${esc(D.name)}</h1><p>${esc([D.people,D.family,D.profile,D.age].filter(Boolean).join(' · '))}</p></div><div class="level"><small>NIV.</small><b>${esc(D.level)}</b></div></header><section class="resources" id="resources"></section><div class="content"><section class="page active" id="play"></section><section class="page" id="fight"></section><section class="page" id="abilities"></section><section class="page" id="stats"></section><section class="page" id="bag"></section><section class="page" id="rest"></section><section class="page" id="notes"></section><p class="source">Source du personnage : ${esc(D.source||'Forge of Heroes')}. Les dés restent physiques ; la fiche assure uniquement le suivi.</p></div></article></main><div class="toast" id="toast" role="status"></div>`;
const $=selector=>document.querySelector(selector);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function renderResources(){S.hp=clamp(S.hp,0,max.hp);S.pc=clamp(S.pc,0,max.pc);S.pm=clamp(S.pm,0,max.pm);S.dr=clamp(S.dr,0,max.dr);S.silver=Math.max(0,Number(S.silver)||0);const rows=[['hp','PV',max.hp],['pc','Chance',max.pc],['pm','Mana',max.pm],['dr','Récup.',max.dr]];$('#resources').innerHTML=rows.map(([k,label,m])=>`<div class="resource"><small>${label}</small><div class="counter"><button data-count="${k}" data-delta="-1" aria-label="Retirer 1 ${label}">−</button><b>${S[k]}/${m}</b><button data-count="${k}" data-delta="1" aria-label="Ajouter 1 ${label}">+</button></div></div>`).join('')+`<div class="resource"><small>Défense</small><b>${esc(D.combat.def)}</b></div><div class="resource"><small>Initiative</small><b>${esc(D.combat.init)}</b></div>`;save()}
function attackHtml(a){const ammo=a.ammo||a.magazine;return`<article class="attack"><div class="attack-head"><h3>${esc(a.name)} · ${signed(a.attack)}</h3><span class="tag">${esc(a.type)}</span></div><p><b>${esc(a.damage)} DM</b> · ${esc(a.range||'—')}${a.damageType?' · '+esc(a.damageType):''}${a.special?' · '+esc(a.special):''}</p>${ammo?`<div class="ability-actions"><span class="tag">Munitions ${Number(S.ammo[a.id]??ammo.current??ammo.capacity)}/${esc(ammo.capacity)}</span><button class="mini-button" data-ammo="${esc(a.id)}" data-ammo-delta="-1">Tirer</button><button class="mini-button" data-ammo="${esc(a.id)}" data-ammo-delta="1">Recharger</button></div>`:''}</article>`}
function abilityHtml(a){const type=actionType(a),u=usage(a),cost=resourceCost(a),used=Number(S.uses[a.id])||0,remaining=u?Math.max(0,u.max-used):null;return`<article class="ability"><div class="ability-head"><div><span class="tag action">${type}</span> <span class="tag">Rang ${a.rank}</span></div>${u?`<span class="tag ${remaining===0?'used':''}">${remaining}/${u.max} disponible</span>`:''}</div><h3>${esc(a.name)}</h3><p><b>${esc(a.path)}</b></p><p>${esc(a.text)}</p>${u||cost?`<div class="ability-actions">${u?`<button class="mini-button primary" data-use="${a.id}" ${remaining===0?'disabled':''}>Utiliser</button><button class="mini-button" data-refund="${a.id}" ${used===0?'disabled':''}>Annuler</button>`:cost?`<button class="mini-button primary" data-spend="${a.id}">Dépenser ${cost.label}</button>`:''}${cost?`<span class="tag">Coût : ${cost.label}</span>`:''}</div>`:''}</article>`}
function renderPlay(){const active=ownedAbilities().filter(a=>actionType(a)!=='Passif'||usage(a)||resourceCost(a));$('#play').innerHTML=`<div class="dashboard"><article class="card"><h2>Valeurs essentielles</h2><div class="value-grid"><div class="value"><small>CONTACT</small><b>${signed(D.combat.contact)}</b></div><div class="value"><small>DISTANCE</small><b>${signed(D.combat.distance)}</b></div><div class="value"><small>MAGIE</small><b>${signed(D.combat.magic)}</b></div><div class="value"><small>DR</small><b>${esc(D.combat.recoveryDie)}</b></div></div></article><article class="state-box"><div class="row-between"><b>États actifs</b><span class="tag">Suivi manuel</span></div><div class="condition-form"><select id="condition-select"><option value="">Ajouter un état…</option>${Object.keys(conditionsInfo).map(x=>`<option>${x}</option>`).join('')}</select><button class="mini-button primary" id="condition-add">Ajouter</button></div><div class="conditions" id="conditions"></div></article></div><div class="section-title">Attaques prêtes</div><div class="list">${(D.attacks||[]).map(attackHtml).join('')||'<div class="empty">Aucune attaque renseignée.</div>'}</div><div class="section-title">Actions propres à ce personnage</div><div class="personal-actions">${active.map(abilityHtml).join('')||'<div class="empty">Les capacités acquises sont passives. Consulte Capacités pour leur texte complet.</div>'}</div>`;renderConditions()}
function renderConditions(){const el=$('#conditions');if(!el)return;el.innerHTML=S.conditions.length?S.conditions.map(x=>`<span class="condition" title="${esc(conditionsInfo[x]||'')}">${esc(x)} <button data-remove-condition="${esc(x)}" aria-label="Retirer ${esc(x)}">×</button></span>`).join(''):'<span class="empty">Aucun état actif.</span>'}
function renderFight(){$('#fight').innerHTML=`<div class="section-title">Mon tour : choisir une formule</div><div class="choice-grid"><article class="choice"><strong>(L) Une action limitée</strong><p>Une capacité notée (L) ou une action complexe occupe normalement tout le tour.</p></article><article class="choice"><strong>(M) + (A)</strong><p>Un mouvement et une attaque, dans l’ordre de ton choix.</p></article><article class="choice"><strong>(M) + (M)</strong><p>Deux mouvements, généralement 20 mètres au total.</p></article></div><div class="notice"><b>Pas d’action bonus en COF2.</b> Une action gratuite (G) s’ajoute seulement si son texte l’autorise.</div><div class="section-title">Actions courantes</div><div class="combat-grid"><article class="choice"><strong>Marcher (M)</strong><p>10 m. Il est possible de dégainer pendant le déplacement.</p></article><article class="choice"><strong>Attaquer (A)</strong><p>1d20 physique + valeur de contact, distance ou magie contre la DEF.</p></article><article class="choice"><strong>Défense partielle (A)</strong><p>+3 en DEF et aux tests opposés pendant 1 round.</p></article><article class="choice"><strong>Défense totale (L)</strong><p>+5 en DEF et aux tests opposés pendant 1 round.</p></article><article class="choice"><strong>Sprinter (L)</strong><p>30 m en ligne droite ; jusqu’au prochain tour, -5 en DEF et dé malus aux tests.</p></article><article class="choice"><strong>Se relever (A)</strong><p>Se relever ou ramasser une arme utilise l’action d’attaque.</p></article></div><div class="section-title">Options utiles</div><div class="rules"><details><summary>Attaque assurée et attaque puissante</summary><div><b>Assurée :</b> +5 en attaque, DM divisés par deux.<br><b>Précise ou violente :</b> -3 en attaque pour +1d4 DM, ou -7 pour +2d4 DM.</div></details><details><summary>Sorts et mana</summary><div>Respecte le type d’action du sort. Son coût normal est égal à son rang. Un sort (A) peut devenir (L) pour coûter 2 PM de moins. La brûlure de mana inflige, pour chaque PM manquant, des DM égaux au dé de récupération et ne permet pas de lancer un soin.</div></details><details><summary>Manœuvres</summary><div>Action limitée, test opposé d’attaque et aucun dégât : distraire, gêner, repousser, bloquer, désarmer, aveugler, renverser ou étourdir. Répéter une manœuvre sur la même cible pendant le combat impose ensuite -5 cumulatif.</div></details><details><summary>Deux armes et dégâts temporaires</summary><div><b>Deux armes (L) :</b> une attaque avec chaque arme, toutes deux avec dé malus ; arme secondaire limitée à 1d6 DM.<br><b>Assommer :</b> dé malus sauf arme adaptée, puis retrancher la FOR de la cible aux DM temporaires.</div></details></div><p class="source">Synthèse COF2 : combat p. 209–221 ; magie et sorts p. 227–228. Le texte officiel et la décision du MJ priment.</p>`}
function renderAbilities(){const used=(D.paths||[]).filter(p=>(p.ranks||[]).some(r=>r.owned)),unused=(D.paths||[]).filter(p=>!(p.ranks||[]).some(r=>r.owned));$('#abilities').innerHTML=`<div class="section-title">Capacités acquises</div><div class="list">${used.map(path=>`<article class="path"><h3>${esc(path.name)}</h3>${path.ranks.filter(r=>r.owned).map(r=>`<div class="rank"><b><span class="check">✓</span>${r.rank}. ${esc(r.name)} <span class="tag action">${actionType(r)}</span></b><p>${esc(r.text)}</p></div>`).join('')}</article>`).join('')}</div><details class="future"><summary>Préparer une montée de niveau</summary><div class="future-content">${used.map(path=>`<h3>${esc(path.name)}</h3>${path.ranks.filter(r=>!r.owned).map(r=>`<p><b>${r.rank}. ${esc(r.name)}</b> — ${esc(r.text)}</p>`).join('')}`).join('')}</div></details><details class="future"><summary>Consulter les autres voies du profil</summary><div class="future-content">${unused.map(path=>`<h3>${esc(path.name)}</h3>${path.ranks.map(r=>`<p><b>${r.rank}. ${esc(r.name)}</b> — ${esc(r.text)}</p>`).join('')}`).join('')||'<p>Aucune autre voie renseignée.</p>'}</div></details>`}
function renderStats(){$('#stats').innerHTML=`<div class="section-title">Caractéristiques</div><div class="stats">${Object.entries(D.stats||{}).map(([k,v])=>`<div class="stat"><small>${esc(k)}</small><b>${signed(v)}</b></div>`).join('')}</div>${D.traits?.length?`<div class="section-title">Traits et restrictions</div><div class="list">${D.traits.map(x=>`<div class="item">${esc(x)}</div>`).join('')}</div>`:''}<div class="section-title">Repères de combat</div><div class="value-grid"><div class="value"><small>DÉF</small><b>${esc(D.combat.def)}</b></div><div class="value"><small>INIT</small><b>${esc(D.combat.init)}</b></div><div class="value"><small>PV MAX</small><b>${max.hp}</b></div><div class="value"><small>PC MAX</small><b>${max.pc}</b></div></div>`}
function renderBag(){$('#bag').innerHTML=`<div class="notice">La modification détaillée des objets et les packs MJ arrivent à l’étape Inventaire. Cette version conserve fidèlement l’équipement actuel et permet déjà de suivre la monnaie.</div><div class="section-title">Équipement actuel</div><div class="list">${(D.equipment||[]).map(x=>`<div class="item">${esc(typeof x==='string'?x:x.name)}</div>`).join('')||'<div class="empty">Aucun équipement renseigné.</div>'}</div><div class="section-title">Monnaie</div><div class="item money"><button class="mini-button" data-silver="-1">−</button><input id="silver-input" type="number" min="0" value="${S.silver}" aria-label="Pièces d’argent"><span>pièces d’argent</span><button class="mini-button" data-silver="1">+</button></div>`}
function renderRest(){$('#rest').innerHTML=`<div class="section-title">Récupération et usages</div><div class="rest-grid"><article class="rest-card"><h3>Dé de récupération</h3><p>Lance physiquement ${esc(D.combat.recoveryDie)} selon la situation décidée par le MJ, puis ajuste tes PV.</p><div class="ability-actions"><button class="mini-button primary" id="spend-dr" ${S.dr<1?'disabled':''}>Dépenser 1 DR</button></div></article><article class="rest-card"><h3>Fin du combat</h3><p>Réactive uniquement les capacités limitées à une utilisation par combat. Les autres ressources ne changent pas.</p><div class="ability-actions"><button class="mini-button" data-reset="combat">Réinitialiser le combat</button></div></article><article class="rest-card"><h3>Nouvelle journée</h3><p>Réactive les capacités quotidiennes. Les PV, PM, PC et DR restent sous contrôle manuel.</p><div class="ability-actions"><button class="mini-button" data-reset="day">Réinitialiser la journée</button></div></article></div><div class="section-title">Capacités suivies</div><div class="list">${ownedAbilities().filter(usage).map(a=>abilityHtml(a)).join('')||'<div class="empty">Aucune capacité à usage limité détectée sur cette fiche.</div>'}</div>`}
function renderNotes(){$('#notes').innerHTML=`<div class="section-title">Informations personnelles</div><div class="field-grid"><label>Joueur<input id="player" value="${esc(S.player)}"></label><label>Idéal héroïque<input id="ideal" value="${esc(S.ideal)}"></label><label>Travers<input id="flaw" value="${esc(S.flaw)}"></label></div><div class="section-title">Notes de partie</div><textarea id="notes-text" placeholder="Noms, indices, objectifs, effets temporaires…">${esc(S.notes)}</textarea>`}
function renderAll(){renderResources();renderPlay();renderFight();renderAbilities();renderStats();renderBag();renderRest();renderNotes()}
function updateAfterAction(){save();renderResources();renderPlay();renderBag();renderRest()}
document.addEventListener('click',event=>{const t=event.target.closest('button');if(!t)return;if(t.dataset.page){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===t));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===t.dataset.page));t.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});return}if(t.dataset.count){const k=t.dataset.count;S[k]=clamp(S[k]+Number(t.dataset.delta),0,max[k]);updateAfterAction();return}if(t.dataset.use){const a=ownedAbilities().find(x=>x.id===t.dataset.use),u=a&&usage(a),cost=a&&resourceCost(a);if(cost&&S[cost.kind]<cost.amount){toast('Ressource insuffisante : '+cost.label+'.');return}if(u&&(S.uses[a.id]||0)<u.max){S.uses[a.id]=(S.uses[a.id]||0)+1;if(cost)S[cost.kind]-=cost.amount;toast(a.name+' marqué comme utilisé.');updateAfterAction()}return}if(t.dataset.spend){const a=ownedAbilities().find(x=>x.id===t.dataset.spend),cost=a&&resourceCost(a);if(cost&&S[cost.kind]>=cost.amount){S[cost.kind]-=cost.amount;toast(cost.label+' dépensé pour '+a.name+'.');updateAfterAction()}else if(cost)toast('Ressource insuffisante : '+cost.label+'.');return}if(t.dataset.refund){S.uses[t.dataset.refund]=Math.max(0,(S.uses[t.dataset.refund]||0)-1);updateAfterAction();return}if(t.dataset.ammo){const a=(D.attacks||[]).find(x=>x.id===t.dataset.ammo),ammo=a&&(a.ammo||a.magazine),cap=Number(ammo?.capacity)||0;S.ammo[t.dataset.ammo]=clamp(S.ammo[t.dataset.ammo]??ammo?.current??cap,0,cap)+Number(t.dataset.ammoDelta);S.ammo[t.dataset.ammo]=clamp(S.ammo[t.dataset.ammo],0,cap);updateAfterAction();return}if(t.id==='condition-add'){const value=$('#condition-select').value;if(value&&!S.conditions.includes(value)){S.conditions.push(value);save();renderConditions()}return}if(t.dataset.removeCondition){S.conditions=S.conditions.filter(x=>x!==t.dataset.removeCondition);save();renderConditions();return}if(t.dataset.silver){S.silver=Math.max(0,S.silver+Number(t.dataset.silver));updateAfterAction();return}if(t.id==='spend-dr'&&S.dr>0){S.dr--;toast('Dé de récupération dépensé. Ajuste les PV après ton lancer.');updateAfterAction();return}if(t.dataset.reset){ownedAbilities().forEach(a=>{const u=usage(a);if(u&&(t.dataset.reset==='day'||u.scope==='combat'))S.uses[a.id]=0});toast(t.dataset.reset==='day'?'Capacités quotidiennes réactivées.':'Capacités de combat réactivées.');updateAfterAction()}});
document.addEventListener('input',event=>{if(event.target.id==='silver-input'){S.silver=Math.max(0,Number(event.target.value)||0);save()}const map={player:'player',ideal:'ideal',flaw:'flaw','notes-text':'notes'};if(map[event.target.id]){S[map[event.target.id]]=event.target.value;save()}});
renderAll();
})();
