'use strict';
const crypto=require('crypto');
const clone=x=>JSON.parse(JSON.stringify(x));
const stable=x=>{if(Array.isArray(x))return x.map(stable);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])]));return x};
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(stable(x))).digest('hex');
const META=new Set(['identity','identite','creationInput','history','audit','migration','updatedAt','createdAt','id','heroLibraryId','historyLog','creationInputNoise','calculationTrace','semanticLedger']);
function stripMetadata(value){if(Array.isArray(value))return value.map(stripMetadata);if(!value||typeof value!=='object')return value;const out={};for(const [k,v] of Object.entries(value))if(!META.has(k))out[k]=stripMetadata(v);return out}
function normalizeMechanicalInput(d){return stripMetadata(clone(d||{}))}
function normalizeMechanicalCharacterState(cs){return stripMetadata(clone(cs||{}))}
function mechanicalHash(cs){return hash(normalizeMechanicalCharacterState(cs))}
function eq(a,b){return JSON.stringify(stable(a))===JSON.stringify(stable(b))}
function deepDiffPaths(a,b,prefix=''){if(eq(a,b))return[];if(Array.isArray(a)||Array.isArray(b)||!a||!b||typeof a!=='object'||typeof b!=='object')return[prefix||'$'];const out=[];for(const k of new Set([...Object.keys(a),...Object.keys(b)])){const p=prefix?prefix+'.'+k:k;out.push(...deepDiffPaths(a[k],b[k],p))}return [...new Set(out)].sort()}
function getPath(o,p){return String(p).split('.').reduce((v,k)=>v==null?undefined:v[k],o)}
function covers(rule,actual){return rule==='$'||rule===actual||actual.startsWith(rule+'.')||rule.startsWith(actual+'.')}
function evaluateMechanicalTransition(before,after,contract={}){const a=normalizeMechanicalCharacterState(before),b=normalizeMechanicalCharacterState(after),actualChangedPaths=deepDiffPaths(a,b),expected=contract.EXPECTED_CHANGED_PATHS||[],unchanged=contract.EXPECTED_UNCHANGED_PATHS||[],allowed=contract.OPTIONAL_ALLOWED_CHANGES||[],missingExpectedChanges=expected.filter(p=>!actualChangedPaths.some(x=>covers(p,x))),unexpectedChanges=actualChangedPaths.filter(x=>![...expected,...allowed].some(p=>covers(p,x))),unchangedViolations=unchanged.filter(p=>actualChangedPaths.some(x=>covers(p,x))),exactValueFailures=[];for(const [p,want] of Object.entries(contract.EXPECTED_VALUES_AFTER||{})){const got=getPath(b,p);if(!eq(got,want))exactValueFailures.push({path:p,expected:want,actual:got})}const status=!missingExpectedChanges.length&&!unexpectedChanges.length&&!unchangedViolations.length&&!exactValueFailures.length?'PASS':'FAIL';return{status,actualChangedPaths,missingExpectedChanges,unexpectedChanges,unchangedViolations,exactValueFailures,beforeHash:hash(a),afterHash:hash(b)}}
function evaluateMechanicalModification(a,b,expectedChanged=[]){return evaluateMechanicalTransition(a,b,{EXPECTED_CHANGED_PATHS:expectedChanged,OPTIONAL_ALLOWED_CHANGES:['$']})}
function evaluateABA(aInitial,aReturned){const initialHash=mechanicalHash(aInitial),returnedHash=mechanicalHash(aReturned),restoredExactly=initialHash===returnedHash;return{initialHash,returnedHash,restoredExactly,status:restoredExactly?'PASS':'FAIL'}}
function evaluateGhostParity(transitioned,fresh){const a=normalizeMechanicalCharacterState(transitioned),b=normalizeMechanicalCharacterState(fresh),residualPaths=deepDiffPaths(b,a),equal=!residualPaths.length;return{transitionedMechanicalHash:hash(a),freshMechanicalHash:hash(b),residualPaths,equal,status:equal?'PASS':'FAIL'}}
function evaluateIllegalReason(errors,expected){const text=(errors||[]).join(' | '),tests=(Array.isArray(expected)?expected:[expected]).filter(Boolean).map(x=>x instanceof RegExp?x:new RegExp(x,'i'));if(!errors||!errors.length)return{classification:'UNEXPECTED_ACCEPTED',status:'FAIL',text};if(!tests.some(re=>re.test(text)))return{classification:'WRONG_REASON',status:'FAIL',text};return{classification:'TARGET_REJECTED',status:'PASS',text}}
function evaluateCoverageGate(rows,required){const by=new Map((rows||[]).map(x=>[x.category,x]));const missing=(required||[]).filter(k=>!by.has(k)||Number(by.get(k).attempted||0)<=0||Number(by.get(k).completed||0)<=0);return{missing,status:missing.length?'FAIL':'PASS'}}
function countUniqueMechanicalInputs(rows){return new Set(rows.map(x=>hash(normalizeMechanicalInput(x)))).size}
function countUniqueMechanicalOutputs(rows){return new Set(rows.map(x=>mechanicalHash(x))).size}
function evaluateIllegalGate(rows){const bad=(rows||[]).filter(x=>Number(x.unexpectedAccepted||0)>0||Number(x.wrongReason||0)>0||Number(x.rejectedForTargetViolation||0)!==Number(x.generated||0));return{badCategories:bad.map(x=>x.category),status:bad.length?'FAIL':'PASS'}}
module.exports={clone,hash,stable,normalizeMechanicalInput,normalizeMechanicalCharacterState,mechanicalHash,deepDiffPaths,getPath,evaluateMechanicalTransition,evaluateMechanicalModification,evaluateABA,evaluateGhostParity,evaluateIllegalReason,evaluateCoverageGate,countUniqueMechanicalInputs,countUniqueMechanicalOutputs,evaluateIllegalGate};
