'use strict';
const fs=require('fs'),path=require('path'),F=require('./forge_product_runner');
const ROOT=path.resolve(__dirname,'..'),env=F.load(),E=env.engine,T=env.db.tables||env.db,C=x=>JSON.parse(JSON.stringify(x));
function fill(s){s.abilityChoices||={};s.profileChoices||={};for(let z=0;z<5;z++)for(const a of E.previewAcquiredAbilities(s))for(const c of E.getPersistentChoicesForAbility(s,a.id)){if(c.id==='preferredWeaponCategory')s.profileChoices[c.id]||='swords';else if(c.id==='extraLanguage')s.profileChoices[c.id]||='celestien';else{const b=s.abilityChoices[a.id]||(s.abilityChoices[a.id]={});if(c.type==='boolean')b[c.id]??=false;else if(c.type==='entity')b[c.id]||={type:'animal',species:'chat',name:'Milo'};else if(c.type==='weapon_multi')b[c.id]=(c.options||[]).slice(0,Math.max(1,c.min||1)).map(x=>x.id);else if(c.options?.[0])b[c.id]??=c.options[0].id}}return s}
function std(profile='class:voleur:cof2-lb-2024'){const s=F.standardState(env.db,profile);if(profile.includes('pretre'))s.profileChoices.priestMode='generalist';return fill(s)}
function ranked(label,rank,otherLabel){const a=T.abilities_class.find(x=>x.label===label),p=T.paths_class.find(x=>x.id===a.path_id),s=std(p.classId),other=otherLabel?T.paths_class.find(x=>x.classId===p.classId&&x.label===otherLabel):T.paths_class.find(x=>x.classId===p.classId&&x.id!==p.id&&!x.additionalMagePath);s.voies.profilePathIds=[p.id,other.id];F.withRank(env.db,s,p.id,rank||a.rank);if(label==='Armes de prédilection')s.profileChoices.preferredWeaponCategory='swords';if(label==='Éduqué')s.profileChoices.extraLanguage='celestien';return fill(s)}
const fixtures=[];const add=(n,name,state,predicate,before)=>fixtures.push({n,name,state,predicate,before});
add(1,'Standard débutant',std(),r=>r.sticky.profileId==='class:voleur:cof2-lb-2024');const pb=std();pb.characteristicMethod={type:'ADVANCED_POINT_BUY'};pb.serieId='advanced';pb.baseCaracs={for:2,agi:2,con:1,per:1,int:0,vol:0,cha:-1};add(2,'Point-buy',pb,r=>!r.errors.length);
add(3,'Mûr + Peau de pierre',ranked('Peau de pierre',2),r=>r.sticky.acquiredAbilities.some(x=>x.label==='Peau de pierre'));
const spec=ranked('Spécialisation',3,'Voie du bouclier');spec.profileChoices.preferredWeaponCategory='swords';const gr=T.profile_rules.find(x=>x.profileId===spec.classeId),shieldPack=gr.initialEquipment.packages.find(x=>x.shieldId);if(shieldPack)spec.equip={initialPackageId:shieldPack.id,armorId:gr.initialEquipment.requiredArmorId||'',shieldId:shieldPack.shieldId,weaponIds:C(shieldPack.weaponIds||[])};add(4,'Vénérable + Spécialisation',fill(spec),r=>r.sticky.acquiredAbilities.some(x=>x.label==='Spécialisation'));
add(5,'Arme à répétition R2',ranked('Arme à répétition',2,'Voie des explosifs'),r=>r.sticky.acquiredAbilities.some(x=>x.label==='Arme à répétition'));
const ca=ranked('Combattant aguerri',3,'Voie de l’artilleur'),cid=Object.keys(ca.abilityChoices).find(x=>x.includes('combattant-aguerri')),cc=E.getPersistentChoicesForAbility(ca,cid)[0],archer=cc.options.find(x=>String(x.label).includes('Archer émérite'));if(archer)ca.abilityChoices[cid][cc.id]=archer.id;const caBefore=C(ca);caBefore.age.categoryId='mature';caBefore.age.spending=caBefore.age.spending.filter(x=>x.rank===2);delete caBefore.abilityChoices[cid];add(6,'Combattant aguerri R3',ca,r=>r.sticky.acquiredAbilities.some(x=>x.label==='Combattant aguerri')&&r.sticky.grantedAbilities.some(x=>x.id===archer.id),caBefore);
const hy=std(),p2='class:arquebusier:cof2-lb-2024',a=hy.voies.profilePathIds[0],b=T.paths_class.find(x=>x.classId===p2&&!x.additionalMagePath);hy.hybrid={enabled:true,gmApproved:true,primaryProfileId:hy.classeId,secondaryProfileId:p2,primaryPathId:a,secondaryPathId:b.id};hy.voies.profilePathIds=[a,b.id];add(7,'Hybride réel',fill(hy),r=>!!r.sticky.hybrid);
const hist=std(),geo=T.history_paths.find(x=>x.label==='Voie des campagnes'||x.name==='Voie des campagnes')||T.history_paths.find(x=>x.category==='geographic'),pro=T.history_paths.find(x=>x.label==='Voie du courtisan'||x.name==='Voie du courtisan')||T.history_paths.find(x=>x.category==='professional');hist.advancedRules.histories=true;hist.advancedRules.age=true;hist.history={geographicPathId:geo.id,professionalPathId:pro.id,rank:1};hist.voies.profilePathIds=[hist.voies.profilePathIds[0]];hist.age={categoryId:'venerable',spending:[2,3,4,5].map(rank=>({pathId:geo.id,rank}))};add(8,'Historique rang 5',fill(hist),r=>r.sticky.historyPath&&r.sticky.characterState.pathAssignments.geographic.rank===5);
const mage=std('class:magicien:cof2-lb-2024'),mp=T.paths_class.filter(x=>x.classId===mage.classeId&&!x.additionalMagePath)[1];mage.voies.mageRank2PathId=mp.id;add(9,'Mage R2',fill(mage),r=>r.sticky.characterState.familyId==='mage'&&r.sticky.acquiredAbilities.some(x=>Number(x.rank)===2));
add(10,'Save/load + Éduqué',ranked('Éduqué',1),r=>r.sticky.characterState.creationDecisions.extraLanguage==='celestien');
const np=std(),npa=T.paths_class.find(x=>x.classId==='class:voleur:cof2-lb-2024'&&x.label==='Voie de l’assassin'),npb=T.paths_class.find(x=>x.classId==='class:arquebusier:cof2-lb-2024'&&x.label==='Voie de l’artilleur');np.profileMode='NO_PROFILE';np.noProfile={enabled:true,primaryPathId:npa.id,pathIds:[npa.id,npb.id]};np.voies.profilePathIds=[npa.id,npb.id];add(11,'Sans profil',fill(np),r=>r.sticky.characterState.profileId===null);
const alc=std();alc.advancedRules.age=true;alc.advancedRules.aLaCarte=true;alc.age={categoryId:'mature',spending:[]};alc.aLaCartePurchases=[{type:'language',language:'sylvestre'},{type:'skill',skill:'Survie'}];add(12,'À la carte',fill(alc),r=>r.sticky.aLaCarte&&r.sticky.aLaCarte.spent===2);
const rows=[];for(const f of fixtures){const file=path.join(ROOT,'MANUAL_FREEZE_PACK',`MANUAL_${String(f.n).padStart(2,'0')}.md`),text=fs.readFileSync(file,'utf8'),r=E.computeCharacterN1(C(f.state)),errors=[...r.errors];let objective=false,statsReflected=false,beforeAfter=true;if(!errors.length){try{objective=!!f.predicate(r)}catch(e){errors.push(String(e.message||e))}const m=text.match(/PV\s+(\d+)\s*;\s*DEF\s+(\d+)\s*;\s*INIT\s+(\d+)\s*;\s*PC\s+(\d+)\s*;\s*PM\s+(\d+)/i);statsReflected=!!m&&[r.sticky.PV,r.sticky.DEF,r.sticky.INIT,r.sticky.PC,r.sticky.PM].every((v,i)=>Number(v)===Number(m[i+1]));if(f.before){const rb=E.computeCharacterN1(C(f.before)),vals=[...text.matchAll(/DEF\s+(\d+)/gi)].map(x=>Number(x[1]));beforeAfter=!rb.errors.length&&vals.includes(Number(rb.sticky.DEF))&&vals.includes(Number(r.sticky.DEF))&&rb.sticky.DEF!==r.sticky.DEF}}
 const status=!errors.length&&objective&&statsReflected&&beforeAfter?'PASS':'FAIL';rows.push({manual:f.n,name:f.name,fixtureErrors:errors,objectiveMatched:objective,computed:r.errors.length?null:{PV:r.sticky.PV,DEF:r.sticky.DEF,INIT:r.sticky.INIT,PC:r.sticky.PC,PM:r.sticky.PM},textReflectsComputedStats:statsReflected,beforeAfterComputedSeparately:beforeAfter,status})}
const out={rows,passed:rows.filter(x=>x.status==='PASS').length,total:12,status:rows.every(x=>x.status==='PASS')?'PASS':'FAIL'};fs.writeFileSync(path.join(ROOT,'FINAL_FREEZE','N1_MANUAL_SCENARIO_ASSERTIONS.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
