'use strict';
const fs=require('fs'),path=require('path'),F=require('./forge_product_runner'),Q=require('./certification_evaluators');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'FINAL_FREEZE'),env=F.load(),E=env.engine,T=env.db.tables||env.db,C=Q.clone;
const write=(n,x)=>fs.writeFileSync(path.join(OUT,n),JSON.stringify(x,null,2));
function fill(s){s.abilityChoices||={};s.profileChoices||={};for(let z=0;z<5;z++)for(const a of E.previewAcquiredAbilities(s))for(const c of E.getPersistentChoicesForAbility(s,a.id)){if(c.id==='preferredWeaponCategory')s.profileChoices[c.id]||='swords';else if(c.id==='extraLanguage')s.profileChoices[c.id]||='celestien';else{const b=s.abilityChoices[a.id]||(s.abilityChoices[a.id]={});if(c.type==='boolean')b[c.id]??=false;else if(c.type==='entity')b[c.id]||={type:'animal',species:'chat',name:'Milo'};else if(c.type==='weapon_multi')b[c.id]=(c.options||[]).slice(0,Math.max(1,c.min||1)).map(x=>x.id);else if(c.options?.[0])b[c.id]??=c.options[0].id}}return s}
function std(profile='class:voleur:cof2-lb-2024',people='people:humain:cof2-lb-2024'){const s=F.standardState(env.db,profile,undefined,people),row=T.peoples.find(x=>x.id===people),sc=row&&row.schema||{};s.peupleChoices={};if(people.includes(':humain:'))s.peupleChoices.humainStat='con';if(sc.bonus&&sc.bonus.mode==='choice')s.peupleChoices.bonusStat=sc.bonus.options[0];if(sc.malus&&sc.malus.mode==='choice')s.peupleChoices.malusStat=sc.malus.options[0];if(profile.includes('pretre'))s.profileChoices.priestMode='generalist';return fill(s)}
function ranked(label,rank){const a=T.abilities_class.find(x=>x.label===label),p=a&&T.paths_class.find(x=>x.id===a.path_id);if(!a||!p)throw Error('missing '+label);const s=std(p.classId),other=T.paths_class.find(x=>x.classId===p.classId&&x.id!==p.id&&!x.additionalMagePath);s.voies.profilePathIds=[p.id,other.id];F.withRank(env.db,s,p.id,rank||a.rank);if(label==='Armes de prédilection')s.profileChoices.preferredWeaponCategory='swords';if(label==='Éduqué')s.profileChoices.extraLanguage='celestien';return fill(s)}
function abilityFixture(label){try{return ranked(label)}catch(_){const ca=T.abilities_class.find(x=>String(x.label).includes(label));if(ca){const p=T.paths_class.find(x=>x.id===ca.path_id);return ranked(ca.label,ca.rank)}const a=[...(T.abilities_people||[]),...(T.abilities_r1_people||[])].find(x=>String(x.label).includes(label)),p=a&&T.paths_people.find(x=>x.id===a.path_id);if(!a||!p)throw Error('missing '+label);const people=p.people_id||(p.allowedPeopleIds||[])[0],s=std('class:voleur:cof2-lb-2024',people);s.voies.peoplePathId=p.id;F.withRank(env.db,s,p.id,a.rank);return fill(s)}}
function noProfile(p1,p2){const a=T.paths_class.find(x=>x.classId===p1&&!x.additionalMagePath&&!x.id.includes('bouclier')),b=T.paths_class.find(x=>x.classId===p2&&!x.additionalMagePath&&!x.id.includes('bouclier')),s=std();s.profileMode='NO_PROFILE';s.noProfile={enabled:true,primaryPathId:a.id,pathIds:[a.id,b.id]};s.voies.profilePathIds=[a.id,b.id];s.equip={weaponIds:[]};return fill(s)}
function hybrid(p1,p2,i=0,j=0){const a=T.paths_class.filter(x=>x.classId===p1&&!x.additionalMagePath)[i],b=T.paths_class.filter(x=>x.classId===p2&&!x.additionalMagePath)[j],s=std(p1);s.hybrid={enabled:true,gmApproved:true,primaryProfileId:p1,secondaryProfileId:p2,primaryPathId:a.id,secondaryPathId:b.id};s.voies.profilePathIds=[a.id,b.id];return fill(s)}
function history(gi,pi,xi){const s=std(),g=T.history_paths.filter(x=>x.category==='geographic')[gi],p=T.history_paths.filter(x=>x.category==='professional')[pi],q=T.paths_class.filter(x=>x.classId===s.classeId&&!x.additionalMagePath)[xi];s.advancedRules.histories=true;s.advancedRules.age=true;s.history={geographicPathId:g.id,professionalPathId:p.id,rank:1};s.voies.profilePathIds=[q.id];s.age={categoryId:'venerable',spending:[2,3,4,5].map(rank=>({pathId:g.id,rank}))};return fill(s)}
function alc(type,value){const s=std();s.advancedRules.age=true;s.advancedRules.aLaCarte=true;s.age={categoryId:'mature',spending:[]};const first=type==='language'?{type,language:value}:type==='skill'?{type,skill:value}:{type,level:value},second=type==='language'?{type:'skill',skill:'Survie'}:{type:'language',language:'sylvestre'};s.aLaCartePurchases=[first,second];return fill(s)}
function compute(s){const r=E.computeCharacterN1(s);return{r,cs:r.sticky&&r.sticky.characterState}}
const ALL=['peopleId','familyId','profileId','characteristics','paths','abilities','spells','resources','derived','equipment','masteries','attacks','languages','religion','hybrid','persistentChoices','creationDecisions','permissions','grantedAbilities','entities','skillBonuses','advancedRules','age','historyPath','pathAssignments','capacityBudget','permanentEffects','conditionalEffects','companions','additionalMagePath','permanentChoices','noProfile','aLaCarte'];
function contract(id,category,a,apply,undo,changed,unchanged=[],exact={}){return{id,category,make:()=>C(a),apply,undo,contract:{EXPECTED_CHANGED_PATHS:changed,EXPECTED_UNCHANGED_PATHS:unchanged,EXPECTED_VALUES_AFTER:exact,OPTIONAL_ALLOWED_CHANGES:ALL.filter(x=>!unchanged.includes(x)&&!changed.includes(x))}}}
const contracts=[];const add=(...x)=>contracts.push(contract(...x));
function scalar(id,cat,a,path,value,changed,unchanged=[],exact={}){const parts=path.split('.'),old=parts.reduce((v,k)=>v[k],a);add(id,cat,a,s=>{let v=s;for(const k of parts.slice(0,-1))v=v[k];v[parts.at(-1)]=value},s=>{let v=s;for(const k of parts.slice(0,-1))v=v[k];v[parts.at(-1)]=old},changed,unchanged,exact)}
const v=std(),g=std('class:guerrier:cof2-lb-2024'),m=std('class:magicien:cof2-lb-2024'),r=std('class:rodeur:cof2-lb-2024');
for(const [i,p] of ['people:elfe-haut:cof2-lb-2024','people:nain:cof2-lb-2024','people:demi-orc:cof2-lb-2024'].entries()){const b=std('class:voleur:cof2-lb-2024',p);add('PEOPLE_'+i,'PEOPLE',v,s=>{s.peupleId=b.peupleId;s.peupleChoices=C(b.peupleChoices);s.voies.peoplePathId=b.voies.peoplePathId},s=>{s.peupleId=v.peupleId;s.peupleChoices=C(v.peupleChoices);s.voies.peoplePathId=v.voies.peoplePathId},['peopleId','characteristics'],['profileId'],{peopleId:p})}
for(const [i,b] of [g,m,r,std('class:arquebusier:cof2-lb-2024')].entries())add('PROFILE_'+i,'PROFILE',v,s=>{s.classeId=b.classeId;s.familleId=b.familleId;s.voies=C(b.voies);s.equip=C(b.equip)},s=>{s.classeId=v.classeId;s.familleId=v.familleId;s.voies=C(v.voies);s.equip=C(v.equip)},['profileId','paths','abilities'],['peopleId','characteristics'],{profileId:b.classeId});
for(const [id,cat] of [['mature','AGE'],['venerable','AGE']]){const b=C(v);b.advancedRules.age=true;b.age={categoryId:id,spending:[]};if(id==='mature')b.age.spending=[{pathId:b.voies.profilePathIds[0],rank:2},{pathId:b.voies.profilePathIds[1],rank:2}];else b.age.spending=[{pathId:b.voies.profilePathIds[0],rank:2},{pathId:b.voies.profilePathIds[0],rank:3},{pathId:b.voies.profilePathIds[1],rank:2}];add('AGE_'+id,cat,v,s=>{s.advancedRules.age=true;s.age=C(b.age)},s=>{s.advancedRules.age=false;delete s.age},['abilities','capacityBudget'],['peopleId','profileId'])}
add('CHAR_FOR_INT','CHARACTERISTIC',v,s=>{const x=s.baseCaracs.for;s.baseCaracs.for=s.baseCaracs.int;s.baseCaracs.int=x},s=>{const x=s.baseCaracs.for;s.baseCaracs.for=s.baseCaracs.int;s.baseCaracs.int=x},['characteristics','derived'],['peopleId','profileId']);
const alt=C(v);alt.voies.profilePathIds=T.paths_class.filter(x=>x.classId===v.classeId&&!x.additionalMagePath).slice(2,4).map(x=>x.id);add('PROFILE_PATHS','PROFILE_PATH',v,s=>s.voies.profilePathIds=C(alt.voies.profilePathIds),s=>s.voies.profilePathIds=C(v.voies.profilePathIds),['paths','abilities'],['peopleId','profileId']);
const vr=C(v);F.withRank(env.db,vr,vr.voies.profilePathIds[0],2);fill(vr);add('PATH_RANK_2','PATH_RANK',v,s=>{s.advancedRules=C(vr.advancedRules);s.age=C(vr.age)},s=>{s.advancedRules=C(v.advancedRules);delete s.age},['paths','abilities','capacityBudget'],['peopleId','profileId']);
for(const [i,[p1,p2]] of [['class:voleur:cof2-lb-2024','class:arquebusier:cof2-lb-2024'],['class:rodeur:cof2-lb-2024','class:guerrier:cof2-lb-2024'],['class:magicien:cof2-lb-2024','class:voleur:cof2-lb-2024']].entries()){const a=hybrid(p1,p2),b=hybrid(p1,p2,1,1);add('HYBRID_PATHS_'+i,'HYBRID_PRIMARY_PATH',a,s=>{s.hybrid.primaryPathId=b.hybrid.primaryPathId;s.voies.profilePathIds[0]=b.hybrid.primaryPathId},s=>{s.hybrid.primaryPathId=a.hybrid.primaryPathId;s.voies.profilePathIds[0]=a.hybrid.primaryPathId},['paths','abilities'],['peopleId']);add('HYBRID_SECONDARY_PATH_'+i,'HYBRID_SECONDARY_PATH',a,s=>{s.hybrid.secondaryPathId=b.hybrid.secondaryPathId;s.voies.profilePathIds[1]=b.hybrid.secondaryPathId},s=>{s.hybrid.secondaryPathId=a.hybrid.secondaryPathId;s.voies.profilePathIds[1]=a.hybrid.secondaryPathId},['paths','abilities'],['peopleId'])}
const h=hybrid('class:voleur:cof2-lb-2024','class:arquebusier:cof2-lb-2024');for(const [cat,key,to] of [['HYBRID_PRIMARY_PROFILE','primaryProfileId','class:rodeur:cof2-lb-2024'],['HYBRID_SECONDARY_PROFILE','secondaryProfileId','class:guerrier:cof2-lb-2024']]){const paths=T.paths_class.filter(x=>x.classId===to&&!x.additionalMagePath),target=std(to);add(cat,cat,h,s=>{s.hybrid[key]=to;const k=key==='primaryProfileId'?'primaryPathId':'secondaryPathId',ix=k==='primaryPathId'?0:1;s.hybrid[k]=paths[0].id;s.voies.profilePathIds[ix]=paths[0].id;if(key==='primaryProfileId'){s.classeId=to;s.familleId=T.classes.find(x=>x.id===to).familleId;s.equip=C(target.equip)}},s=>{Object.assign(s,C(h))},['hybrid','paths','abilities'],['peopleId'])}
add('HYBRID_APPROVAL','HYBRID_APPROVAL',h,s=>s.hybrid.gmApproved=false,s=>s.hybrid.gmApproved=true,[],[],{});contracts.at(-1).expectedError=/validation du MJ/i;
for(const [id,cat,a,b] of [['H_ORIGIN','HISTORY_ORIGIN',history(0,0,0),history(1,0,0)],['H_PRO','HISTORY_PROFESSION',history(0,0,0),history(0,1,0)],['H_PATH','HISTORY_PROFILE_PATH',history(0,0,0),history(0,0,1)]])add(id,cat,a,s=>{s.history=C(b.history);s.voies=C(b.voies);s.age=C(b.age)},s=>{s.history=C(a.history);s.voies=C(a.voies);s.age=C(a.age)},id==='H_PATH'?['abilities']:['abilities','historyPath'],['peopleId']);
for(const [i,[p1,p2,p3]] of [['class:voleur:cof2-lb-2024','class:guerrier:cof2-lb-2024','class:magicien:cof2-lb-2024'],['class:rodeur:cof2-lb-2024','class:magicien:cof2-lb-2024','class:guerrier:cof2-lb-2024']].entries()){const a=noProfile(p1,p2),b=noProfile(p3,p2);add('NP_A_'+i,'NO_PROFILE_PATH_A',a,s=>{s.voies.profilePathIds[0]=b.voies.profilePathIds[0];s.noProfile.primaryPathId=b.noProfile.primaryPathId;s.noProfile.pathIds=C(s.voies.profilePathIds)},s=>{s.voies.profilePathIds[0]=a.voies.profilePathIds[0];s.noProfile.primaryPathId=a.noProfile.primaryPathId;s.noProfile.pathIds=C(s.voies.profilePathIds)},['paths','abilities'],['profileId','peopleId'],{profileId:null});const c=noProfile(p1,p3);add('NP_B_'+i,'NO_PROFILE_PATH_B',a,s=>{s.voies.profilePathIds[1]=c.voies.profilePathIds[1];s.noProfile.pathIds=C(s.voies.profilePathIds)},s=>{s.voies.profilePathIds[1]=a.voies.profilePathIds[1];s.noProfile.pathIds=C(s.voies.profilePathIds)},['paths','abilities'],['profileId','peopleId'],{profileId:null})}
const mage=C(m),mp=T.paths_class.filter(x=>x.classId===m.classeId&&!x.additionalMagePath)[1];add('MAGE_R2','MAGE_R2_PATH',mage,s=>s.voies.mageRank2PathId=mp.id,s=>s.voies.mageRank2PathId=mage.voies.mageRank2PathId,['abilities','spells'],['profileId']);
for(const [type,a,b] of [['LANGUAGE',alc('language','sylvestre'),alc('language','runique')],['SKILL',alc('skill','Survie'),alc('skill','Discrétion')],['ARMOR',alc('language','sylvestre'),(()=>{const x=alc('language','sylvestre');x.aLaCartePurchases=[{type:'armor',level:2},{type:'language',language:'sylvestre'}];return x})()],['WEAPON',alc('language','sylvestre'),(()=>{const x=alc('language','sylvestre');x.aLaCartePurchases=[{type:'weapons',level:2},{type:'language',language:'sylvestre'}];return x})()]])add('ALC_'+type,'A_LA_CARTE_'+type,a,s=>s.aLaCartePurchases=C(b.aLaCartePurchases),s=>s.aLaCartePurchases=C(a.aLaCartePurchases),type==='LANGUAGE'?['aLaCarte','languages']:type==='SKILL'?['aLaCarte','skillBonuses']:['aLaCarte','permissions'],['peopleId','profileId']);
const stone=ranked('Peau de pierre',2),sid=Object.keys(stone.abilityChoices).find(x=>x.includes('peau-de-pierre')),sk=Object.keys(stone.abilityChoices[sid])[0],sv=stone.abilityChoices[sid][sk];add('STONE_CHOICE','ABILITY_CHOICE',stone,s=>s.abilityChoices[sid][sk]=sv==='AGI'?'CON':'AGI',s=>s.abilityChoices[sid][sk]=sv,['derived.DEF','persistentChoices'],['peopleId','profileId','languages']);
const grant=ranked('Combattant aguerri',3),gid=Object.keys(grant.abilityChoices).find(x=>x.includes('combattant-aguerri')),gk=Object.keys(grant.abilityChoices[gid])[0],gc=E.getPersistentChoicesForAbility(grant,gid).find(x=>x.id===gk),gv=grant.abilityChoices[gid][gk],gn=gc.options.find(x=>x.id!==gv).id;add('GRANT_SWITCH','GRANT_CHOICE',grant,s=>s.abilityChoices[gid][gk]=gn,s=>s.abilityChoices[gid][gk]=gv,['persistentChoices'],['peopleId','profileId']);
const pred=ranked('Armes de prédilection',1);scalar('PREFERRED','PREFERRED_WEAPON_CATEGORY',pred,'profileChoices.preferredWeaponCategory','axes',['creationDecisions','attacks'],['derived.PV','languages']);const edu=ranked('Éduqué',1);scalar('LANGUAGE','EXTRA_LANGUAGE',edu,'profileChoices.extraLanguage','runique',['creationDecisions','languages'],['derived.PV','profileId']);
for(const [cat,field] of [['WEAPON','weaponIds'],['SHIELD','shieldId']]){const a=std('class:barbare:cof2-lb-2024'),rule=T.profile_rules.find(x=>x.profileId===a.classeId),packs=rule.initialEquipment.packages,b=C(a),p=packs.find(x=>JSON.stringify(x[field]||null)!==JSON.stringify(a.equip[field]||null))||packs.at(-1);b.equip={initialPackageId:p.id,armorId:rule.initialEquipment.requiredArmorId||'',shieldId:p.shieldId||'',weaponIds:C(p.weaponIds||[])};add(cat,cat,a,s=>s.equip=C(b.equip),s=>s.equip=C(a.equip),cat==='WEAPON'?['equipment','attacks']:['equipment','derived.DEF'],['peopleId','profileId'])}
const heavy=ranked('Armure lourde',3),hid=Object.keys(heavy.abilityChoices).find(x=>x.includes('armure-lourde')),hk=Object.keys(heavy.abilityChoices[hid])[0],hv=heavy.abilityChoices[hid][hk];add('ARMOR_HEAVY_CHOICE','ARMOR',heavy,s=>s.abilityChoices[hid][hk]=hv==='DEF_PLUS_1'?'PLATE_MASTERY':'DEF_PLUS_1',s=>s.abilityChoices[hid][hk]=hv,['persistentChoices','permissions'],['peopleId','profileId']);
for(const [i,[a,b]] of [['for','agi'],['agi','cha'],['int','vol'],['cha','per']].entries())add('CHAR_SWAP_'+i,'CHARACTERISTIC',v,s=>{const x=s.baseCaracs[a];s.baseCaracs[a]=s.baseCaracs[b];s.baseCaracs[b]=x},s=>{const x=s.baseCaracs[a];s.baseCaracs[a]=s.baseCaracs[b];s.baseCaracs[b]=x},['characteristics','derived'],['peopleId','profileId']);
const vp=T.paths_class.filter(x=>x.classId===v.classeId&&!x.additionalMagePath);for(const [i,ids] of [[vp[0].id,vp[2].id],[vp[0].id,vp[3].id],[vp[1].id,vp[2].id],[vp[1].id,vp[3].id]].entries())add('PROFILE_PATH_VARIANT_'+i,'PROFILE_PATH',v,s=>s.voies.profilePathIds=C(ids),s=>s.voies.profilePathIds=C(v.voies.profilePathIds),['paths','abilities'],['peopleId','profileId']);
for(const [i,value] of ['maces','spears','thrown'].entries())scalar('PREFERRED_VARIANT_'+i,'PREFERRED_WEAPON_CATEGORY',pred,'profileChoices.preferredWeaponCategory',value,['creationDecisions'],['derived.PV','languages']);
for(const [i,value] of ['sylvestre','draconique'].entries())scalar('LANGUAGE_VARIANT_'+i,'EXTRA_LANGUAGE',edu,'profileChoices.extraLanguage',value,['creationDecisions','languages'],['derived.PV','profileId']);
const results=[],abas=[];for(const d of contracts){const a=d.make(),ra=compute(a),work=C(a);d.apply(work);const rb=compute(work);let ev;if(d.expectedError)ev=Q.evaluateIllegalReason(rb.r.errors,d.expectedError);else ev=!ra.r.errors.length&&!rb.r.errors.length?Q.evaluateMechanicalTransition(ra.cs,rb.cs,d.contract):{status:'FAIL',errors:{A:ra.r.errors,B:rb.r.errors}};results.push({id:d.id,category:d.category,contract:d.contract,errors:{A:ra.r.errors,B:rb.r.errors},evaluation:ev,status:ev.status});d.undo(work);const rr=compute(work),aba=!ra.r.errors.length&&!rr.r.errors.length?Q.evaluateABA(ra.cs,rr.cs):{status:'FAIL',errors:rr.r.errors};abas.push({id:d.id,category:d.category,evaluation:aba,status:aba.status})}
const categories=[...new Set(contracts.map(x=>x.category))],missing=results.reduce((n,x)=>n+(x.evaluation.missingExpectedChanges||[]).length,0),unexpected=results.reduce((n,x)=>n+(x.evaluation.unexpectedChanges||[]).length+(x.evaluation.unchangedViolations||[]).length,0),exactTotal=results.reduce((n,x)=>n+Object.keys(x.contract.EXPECTED_VALUES_AFTER||{}).length,0),exactPass=exactTotal-results.reduce((n,x)=>n+(x.evaluation.exactValueFailures||[]).length,0);
write('N1_PRECISION_TRANSITION_CONTRACTS.json',{categories,contracts:contracts.map(x=>({id:x.id,category:x.category,...x.contract,expectedError:String(x.expectedError||'')})),total:contracts.length});write('N1_PRECISION_TRANSITION_RESULTS.json',{results,passed:results.filter(x=>x.status==='PASS').length,total:results.length,missingExpectedChanges:missing,unexpectedChanges:unexpected,exactValueAssertions:{passed:exactPass,total:exactTotal},status:results.every(x=>x.status==='PASS')?'PASS':'FAIL'});write('N1_PRECISION_ABA.json',{results:abas,passed:abas.filter(x=>x.status==='PASS').length,total:abas.length,status:abas.every(x=>x.status==='PASS')?'PASS':'FAIL'});

function toProfileTarget(work,target){work.classeId=target.classeId;work.familleId=target.familleId;work.voies=C(target.voies);work.equip=C(target.equip);work.profileMode=target.profileMode||'PROFILE';delete work.hybrid;delete work.noProfile;work.advancedRules=C(target.advancedRules);delete work.age;delete work.history;work.aLaCartePurchases=[]}
const ghostFixtures=[['HEAVY_ARMOR_TO_ROGUE',ranked('Armure lourde',3),v,['persistentChoices','abilities']],['REPEATING_TO_WARRIOR',ranked('Arme à répétition',2),g,['persistentChoices','attacks']],['GRANT_TO_ROGUE',grant,v,['grantedAbilities','persistentChoices']],['MAGE_TO_WARRIOR',m,g,['spells','resources.mana']],['WARRIOR_TO_MAGE',g,m,['masteries']],['HYBRID_TO_STANDARD',h,v,['hybrid']],['NO_PROFILE_TO_STANDARD',noProfile('class:voleur:cof2-lb-2024','class:guerrier:cof2-lb-2024'),v,['profileId']],['HISTORY_TO_STANDARD',history(0,0,0),v,['historyPath']],['ALC_OFF',alc('language','sylvestre'),v,['languages','skillBonuses']],['EDUQUE_TO_OTHER',edu,v,['creationDecisions.extraLanguage']],['PREFERRED_TO_OTHER',pred,v,['creationDecisions.preferredWeaponCategory']],['STONE_REMOVED',stone,v,['persistentChoices']],['FAMILIAR_REMOVED',abilityFixture('Familier'),v,['entities']]];
const ghosts=[];for(const [id,start,target,removed] of ghostFixtures){const work=C(start);toProfileTarget(work,target);const tr=compute(work),fr=compute(C(target)),ev=!tr.r.errors.length&&!fr.r.errors.length?Q.evaluateGhostParity(tr.cs,fr.cs):{status:'FAIL',residualPaths:[],errors:{transitioned:tr.r.errors,fresh:fr.r.errors}};const observed=removed.map(p=>({path:p,transitioned:Q.getPath(Q.normalizeMechanicalCharacterState(tr.cs||{}),p),fresh:Q.getPath(Q.normalizeMechanicalCharacterState(fr.cs||{}),p),removed:JSON.stringify(Q.getPath(Q.normalizeMechanicalCharacterState(tr.cs||{}),p))===JSON.stringify(Q.getPath(Q.normalizeMechanicalCharacterState(fr.cs||{}),p))}));ghosts.push({scenario:id,transitionOperations:['profile/family','selected paths','equipment','mode/rules toggles'],removedEffectsExpected:removed,removedEffectsObserved:observed,unexpectedResiduals:ev.residualPaths||[],transitionedMechanicalHash:ev.transitionedMechanicalHash,freshMechanicalHash:ev.freshMechanicalHash,status:ev.status})}
write('N1_REAL_GHOST_TRANSITIONS_V2.json',{rows:ghosts,passed:ghosts.filter(x=>x.status==='PASS').length,total:ghosts.length,status:ghosts.every(x=>x.status==='PASS')?'PASS':'FAIL'});write('N1_GHOST_RESIDUAL_PATHS.json',{paths:ghosts.flatMap(x=>x.unexpectedResiduals.map(path=>({scenario:x.scenario,path}))),count:ghosts.reduce((n,x)=>n+x.unexpectedResiduals.length,0)});

const fakeA={derived:{DEF:13,PV:10},languages:['commun'],permissions:{}},fakeDef={derived:{DEF:14,PV:10},languages:['commun'],permissions:{}},fakeLang={derived:{DEF:13,PV:10},languages:['commun','runique'],permissions:{}},fakeExtra={derived:{DEF:14,PV:11},languages:['commun'],permissions:{}},fakeWrong={derived:{DEF:15,PV:10},languages:['commun'],permissions:{}},ghosted=C(fakeDef);ghosted.persistentChoices={obsolete:true};const identicalInputs=Array.from({length:100},(_,i)=>({baseCaracs:{for:1},identite:{nom:'N'+i},id:i,creationInputNoise:i})),identicalOutputs=Array.from({length:100},(_,i)=>({derived:{DEF:13},identity:{nom:'N'+i},id:i,creationInput:{noise:i}}));
const anti={fakeABAResultRejected:Q.evaluateABA(fakeA,fakeDef).status==='FAIL',wrongExpectedPathRejected:Q.evaluateMechanicalTransition(fakeA,fakeLang,{EXPECTED_CHANGED_PATHS:['derived.DEF'],OPTIONAL_ALLOWED_CHANGES:['languages']}).status==='FAIL',unexpectedPathRejected:Q.evaluateMechanicalTransition(fakeA,fakeExtra,{EXPECTED_CHANGED_PATHS:['derived.DEF'],EXPECTED_UNCHANGED_PATHS:['derived.PV']}).status==='FAIL',wrongExactValueRejected:Q.evaluateMechanicalTransition(fakeA,fakeWrong,{EXPECTED_CHANGED_PATHS:['derived.DEF'],EXPECTED_VALUES_AFTER:{'derived.DEF':14}}).status==='FAIL',realGhostPathReported:Q.evaluateGhostParity(ghosted,fakeDef).residualPaths.includes('persistentChoices'),wrongIllegalReasonRejected:Q.evaluateIllegalReason(['Dépense PCap : budget incorrect.'],/compétence inconnue/i).classification==='WRONG_REASON',identityOnlyModificationRejected:Q.evaluateMechanicalTransition(fakeA,C(fakeA),{EXPECTED_CHANGED_PATHS:['derived.DEF']}).status==='FAIL',metadataOnlyUniquenessCollapsed:Q.countUniqueMechanicalInputs(identicalInputs)===1&&Q.countUniqueMechanicalOutputs(identicalOutputs)===1,missingCategoryRejected:Q.evaluateCoverageGate([{category:'A',attempted:1,completed:1}],['A','AGE']).status==='FAIL',unexpectedIllegalAcceptanceRejected:Q.evaluateIllegalGate([{category:'X',generated:10,rejectedForTargetViolation:9,wrongReason:0,unexpectedAccepted:1}]).status==='FAIL'};anti.passed=Object.values(anti).filter(x=>x===true).length;anti.total=10;anti.status=anti.passed===anti.total?'PASS':'FAIL';write('N1_ANTI_FALSE_GREEN_V2.json',anti);

const negatives=[];function neg(rule,state,mut,re){const pos=compute(fill(C(state))),bad=C(state);mut(bad);const out=compute(bad),ev=Q.evaluateIllegalReason(out.r.errors,re);negatives.push({rule,positiveControl:pos.r.errors,expectedErrorPattern:String(re),actualErrors:out.r.errors,classification:ev.classification,status:!pos.r.errors.length&&ev.status==='PASS'?'PASS':'FAIL'})}
neg('A_LA_CARTE_SKILL_FAKE',alc('skill','Survie'),s=>s.aLaCartePurchases=[{type:'skill',skill:'FAKE'},{type:'language',language:'sylvestre'}],/compétence inconnue/i);neg('A_LA_CARTE_LANGUAGE_KNOWN',alc('language','sylvestre'),s=>s.aLaCartePurchases=[{type:'language',language:'commun'},{type:'skill',skill:'Survie'}],/langue .*déjà connue|langue automatique/i);neg('PRIEST_MODE_INVALID',std('class:pretre:cof2-lb-2024'),s=>s.profileChoices.priestMode='FAKE',/Prêtre : choisir généraliste ou spécialiste/i);const priest=std('class:pretre:cof2-lb-2024');priest.profileChoices.priestMode='specialist';const religion=T.religions_n1.find(x=>x.status==='SOURCE_VERIFIED');if(religion){priest.profileChoices.deityId=religion.id;priest.profileChoices.sacredWeaponId=religion.sacredWeaponId;priest.profileChoices.divineAbilityId=religion.divineAbilityId;if(religion.divineRank===1)priest.profileChoices.replacedPriestPathId=priest.voies.profilePathIds[0];neg('RELIGION_INVALID',priest,s=>s.profileChoices.deityId='religion:fake',/religion inconnue/i)}
for(const label of ['Peau de pierre','Armure lourde','Arme à répétition','Combattant aguerri','Familier']){const s=abilityFixture(label),row=E.previewAcquiredAbilities(s).find(x=>String(x.label).includes(label));if(!row)continue;const aid=row.id;neg('REQUIRED_'+label,s,x=>delete x.abilityChoices[aid],/choix obligatoire|requis|minimum|capacité accordée/i);neg('DOMAIN_'+label,s,x=>{const b=x.abilityChoices[aid],k=Object.keys(b)[0];b[k]=k==='repeatingWeapons'?['weapon:fake']:k==='familiar'?{type:'FAKE'}:'FAKE'},label==='Arme à répétition'?/arme .*non possédée|inéligible/i:label==='Combattant aguerri'?/Combattant aguerri : option illégale|capacité accordée illégale/i:label==='Familier'?/type obligatoire|species obligatoire|entité/i:/choix .*illégal|valeur .*illégale/i)}
const nPass=negatives.filter(x=>x.status==='PASS').length;write('N1_TARGETED_NEGATIVE_REASON_PARITY_V2.json',{rows:negatives,passed:nPass,total:negatives.length,wrongReasonRejections:negatives.filter(x=>x.classification==='WRONG_REASON').length,priestMode:negatives.find(x=>x.rule==='PRIEST_MODE_INVALID')?.status||'FAIL',religion:religion?(negatives.find(x=>x.rule==='RELIGION_INVALID')?.status||'FAIL'):'NOT_APPLICABLE',status:nPass===negatives.length?'PASS':'FAIL'});
console.log(JSON.stringify({contracts:[results.filter(x=>x.status==='PASS').length,results.length],aba:[abas.filter(x=>x.status==='PASS').length,abas.length],ghost:[ghosts.filter(x=>x.status==='PASS').length,ghosts.length],anti:[anti.passed,anti.total],negative:[nPass,negatives.length]},null,2));
