'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),F=require('./forge_product_runner');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'FINAL_FREEZE'),env=F.load(),E=env.engine,T=env.db.tables||env.db;
const clone=x=>JSON.parse(JSON.stringify(x)),sha=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex'),write=(n,x)=>fs.writeFileSync(path.join(OUT,n),JSON.stringify(x,null,2));
let seed=0x6f683231;function rnd(){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296}const pick=a=>a[Math.floor(rnd()*a.length)];function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalizeMechanicalInput(d){const x=clone(d||{});for(const k of ['identite','identity','heroLibraryId','updatedAt','createdAt','historyLog','audit'])delete x[k];return x}
function normalizeMechanicalCharacterState(cs){const x=clone(cs||{});for(const k of ['identity','identite','creationInput','history','audit','migration','updatedAt','createdAt','id','heroLibraryId'])delete x[k];return x}
const mech=r=>r&&!r.errors.length?normalizeMechanicalCharacterState(r.sticky.characterState):null;
function fill(s){s.abilityChoices||={};s.profileChoices||={};for(let z=0;z<4;z++)for(const a of E.previewAcquiredAbilities(s))for(const c of E.getPersistentChoicesForAbility(s,a.id)){if(c.id==='preferredWeaponCategory')s.profileChoices[c.id]||='swords';else if(c.id==='extraLanguage')s.profileChoices[c.id]||='celestien';else{const b=s.abilityChoices[a.id]||(s.abilityChoices[a.id]={});if(c.type==='boolean')b[c.id]??=false;else if(c.type==='entity')b[c.id]||={type:'animal',species:'animal familier',name:'Milo'};else if(c.type==='weapon_multi')b[c.id]=(c.options||[]).slice(0,Math.max(1,c.min||1)).map(x=>x.id);else if(b[c.id]==null&&c.options&&c.options[0])b[c.id]=c.options[0].id}}return s}
const profiles=T.classes,peoples=T.peoples;
function standard(profile=pick(profiles).id,people=pick(peoples).id){let s;try{s=F.standardState(env.db,profile,undefined,people)}catch{return standard(profile,'people:humain:cof2-lb-2024')}if(profile.includes('pretre'))s.profileChoices.priestMode='generalist';return fill(s)}
function vary(s){const v=shuffle([3,2,1,1,0,0,-1]),k=['for','agi','con','per','int','vol','cha'];s.baseCaracs=Object.fromEntries(k.map((x,i)=>[x,v[i]]));return fill(s)}
function hybrid(){const a=standard(),p1=T.classes.find(x=>x.id===a.classeId),p2=pick(profiles.filter(x=>x.id!==p1.id)),x1=T.paths_class.find(x=>x.classId===p1.id&&!x.additionalMagePath),x2=T.paths_class.find(x=>x.classId===p2.id&&!x.additionalMagePath);a.hybrid={enabled:true,gmApproved:true,primaryProfileId:p1.id,secondaryProfileId:p2.id,primaryPathId:x1.id,secondaryPathId:x2.id};a.voies.profilePathIds=[x1.id,x2.id];return fill(a)}
function noProfile(){const a=standard(),p1=pick(T.paths_class.filter(x=>!x.additionalMagePath)),p2=pick(T.paths_class.filter(x=>!x.additionalMagePath&&x.id!==p1.id));a.profileMode='NO_PROFILE';a.noProfile={enabled:true,primaryPathId:p1.id,pathIds:[p1.id,p2.id]};a.voies.profilePathIds=[p1.id,p2.id];a.equip={weaponIds:[]};return fill(a)}
function aged(){const a=standard(),rank=rnd()<.5?2:3;F.withRank(env.db,a,a.voies.profilePathIds[0],rank);return fill(a)}
function history(high=false){const a=standard(),g=pick(T.history_paths.filter(x=>x.category==='geographic')),p=pick(T.history_paths.filter(x=>x.category==='professional'));a.advancedRules.histories=true;a.history={geographicPathId:g.id,professionalPathId:p.id,rank:1};a.voies.profilePathIds=[a.voies.profilePathIds[0]];if(high){a.advancedRules.age=true;a.age={categoryId:'venerable',spending:[2,3,4,5].map(rank=>({pathId:g.id,rank}))}}return fill(a)}
function alc(){const a=standard('class:voleur:cof2-lb-2024');a.advancedRules.age=true;a.advancedRules.aLaCarte=true;a.age={categoryId:'mature',spending:[]};a.aLaCartePurchases=[{type:'language',language:pick(['sylvestre','celestien','orc'])},{type:'skill',skill:pick(['Survie','Discrétion','Vigilance'])}];return fill(a)}
function mage(){return standard(pick(profiles.filter(x=>x.familleId==='mage')).id)}
function combined(){const a=noProfile();a.advancedRules.age=true;a.age={categoryId:'mature',spending:a.voies.profilePathIds.map(pathId=>({pathId,rank:2}))};return fill(a)}
const strata=[['standard',20000,standard],['advanced-age',5000,aged],['hybrid',5000,hybrid],['no-profile',5000,noProfile],['history',5000,()=>history(rnd()<.4)],['a-la-carte',5000,alc],['mage-advanced',2500,mage],['combined-advanced',2500,combined]];
const startedAt=new Date().toISOString(),legal=[],strataResult={},uIn=new Set,uOut=new Set,uBuild=new Set;let legalPass=0;
for(const [name,quota,factory] of strata){let pass=0,attempts=0;while(pass<quota&&attempts<quota*50){attempts++;let d;try{d=vary(factory())}catch{continue}const r=E.computeCharacterN1(d);if(r.errors.length)continue;pass++;legalPass++;legal.push(d);uIn.add(sha(normalizeMechanicalInput(d)));uOut.add(sha(normalizeMechanicalCharacterState(r.sticky.characterState)));uBuild.add(sha({mode:name,people:d.peupleId,profile:d.classeId,paths:d.voies.profilePathIds,age:d.age&&d.age.categoryId,choices:d.abilityChoices,alc:d.aLaCartePurchases,stats:d.baseCaracs}))}strataResult[name]={quota,pass,attempts}}
const legalFuzz={pass:legalPass,total:50000,strata:strataResult,uniqueMechanicalInputs:uIn.size,uniqueMechanicalOutputs:uOut.size,uniqueBuildSignatures:uBuild.size};
const defs={
 CHARACTERISTIC_OUT_OF_RANGE:{mut:s=>s.baseCaracs.for=99,re:/hors limites|Caractéristiques|série officielle/i},PATH_INVALID:{mut:s=>s.voies.profilePathIds[0]='path:fake',re:/voie|introuvable|inconnue/i},PATH_COUNT:{mut:s=>s.voies.profilePathIds=[],re:/exactement deux voies|voies de profil/i},
 HYBRID_SAME_PROFILE:{base:hybrid,mut:s=>s.hybrid.secondaryProfileId=s.hybrid.primaryProfileId,re:/deux profils distincts/i},HYBRID_NO_APPROVAL:{base:hybrid,mut:s=>s.hybrid.gmApproved=false,re:/validation du MJ/i},HYBRID_WRONG_PATH_ORIGIN:{base:hybrid,mut:s=>s.voies.profilePathIds.reverse(),re:/voie principale|voie secondaire|origine falsifiée/i},
 HISTORY_MISSING:{base:()=>history(false),mut:s=>s.history={},re:/Historique|géographique|professionnelle/i},HISTORY_SECOND_PROFILE_PATH:{base:()=>history(false),mut:s=>s.voies.profilePathIds.push(T.paths_class.find(x=>x.id!==s.voies.profilePathIds[0]).id),re:/Historique|une seule voie/i},NO_PROFILE_WRONG_PATH_COUNT:{base:noProfile,mut:s=>s.voies.profilePathIds.pop(),re:/Sans profil.*exactement deux/i},
 A_LA_CARTE_OUT_OF_DOMAIN:{base:alc,mut:s=>s.aLaCartePurchases=[{type:'skill',skill:'FAKE'}],re:/la carte|compétence|catalogue/i},A_LA_CARTE_OVER_BUDGET:{base:alc,mut:s=>s.aLaCartePurchases.push({type:'skill',skill:'Vigilance'}),re:/points|budget|dépens/i},EXTRA_LANGUAGE_DUPLICATE:{mut:s=>s.languages={selected:['commun','commun']},re:/langue|doublon/i},EXTRA_LANGUAGE_INVALID:{mut:s=>s.languages={selected:['FAKE']},re:/langue|illégal|catalogue/i},
 ARMOR_NOT_MASTERED:{mut:s=>s.equip.armorId='armor:fake',re:/armure/i},SHIELD_NOT_MASTERED:{mut:s=>s.equip.shieldId='shield:fake',re:/bouclier/i},WEAPON_NOT_MASTERED:{mut:s=>s.equip.weaponIds=['weapon:fake'],re:/arme/i},PREFERRED_WEAPON_INVALID:{base:()=>{const s=standard('class:guerrier:cof2-lb-2024'),p=T.paths_class.find(x=>x.classId===s.classeId&&x.id.includes('maitre-d-armes')),o=T.paths_class.find(x=>x.classId===s.classeId&&x.id!==p.id&&!x.additionalMagePath);s.voies.profilePathIds=[p.id,o.id];s.profileChoices.preferredWeaponCategory='swords';return fill(s)},mut:s=>s.profileChoices.preferredWeaponCategory='laser',re:/prédilection|catégorie|choix/i},MAGE_R2_INVALID:{base:mage,mut:s=>s.voies.mageRank2PathId='',re:/Mage N1.*rang 2/i},
 HYBRID_PATH_COUNT:{base:hybrid,mut:s=>s.voies.profilePathIds.pop(),re:/exactement deux voies/i},NO_PROFILE_DUPLICATE_PATH:{base:noProfile,mut:s=>s.voies.profilePathIds[1]=s.voies.profilePathIds[0],re:/Sans profil.*distinctes/i}
};
const cats=Object.fromEntries(Object.keys(defs).map(k=>[k,{category:k,generated:0,rejectedForTargetViolation:0,wrongReason:0,unexpectedAccepted:0,samples:[]}])) ;let rejected=0,wrongReason=0,accepted=0;
for(let i=0;i<50000;i++){const k=Object.keys(defs)[i%Object.keys(defs).length],d=defs[k],row=cats[k];let a;try{a=fill((d.base||standard)())}catch{i--;continue}if(E.computeCharacterN1(a).errors.length){i--;continue}const b=clone(a);d.mut(b);const bad=E.computeCharacterN1(b),msg=bad.errors.join(' | ');row.generated++;if(bad.errors.length&&d.re.test(msg)){row.rejectedForTargetViolation++;rejected++}else if(bad.errors.length){row.wrongReason++;wrongReason++;if(row.samples.length<2)row.samples.push({errors:bad.errors})}else{row.unexpectedAccepted++;accepted++;if(row.samples.length<2)row.samples.push({accepted:true})}}
const ops=[
 ['CHARACTERISTIC',s=>{const v=s.baseCaracs.for;s.baseCaracs.for=s.baseCaracs.agi;s.baseCaracs.agi=v;return t=>{const q=t.baseCaracs.for;t.baseCaracs.for=t.baseCaracs.agi;t.baseCaracs.agi=q}}],
 ['PREFERRED_WEAPON_CATEGORY',s=>{const o=s.profileChoices.preferredWeaponCategory;s.profileChoices.preferredWeaponCategory=o==='axes'?'swords':'axes';return t=>t.profileChoices.preferredWeaponCategory=o}],
 ['EXTRA_LANGUAGE',s=>{const o=s.profileChoices.extraLanguage;s.profileChoices.extraLanguage=o==='celestien'?'sylvestre':'celestien';return t=>t.profileChoices.extraLanguage=o}],
 ['WEAPON',s=>{const o=clone(s.equip.weaponIds);s.equip.weaponIds=o.slice().reverse();return t=>t.equip.weaponIds=o}],
 ['ABILITY_CHOICE',s=>{const o=clone(s.abilityChoices);for(const b of Object.values(s.abilityChoices||{}))for(const k of Object.keys(b))if(typeof b[k]==='boolean')b[k]=!b[k];return t=>t.abilityChoices=o}],
 ['A_LA_CARTE_PURCHASE',s=>{const o=clone(s.aLaCartePurchases||[]);if(s.advancedRules.aLaCarte)s.aLaCartePurchases=o.slice().reverse();return t=>t.aLaCartePurchases=o}],
 ['PATH_ORDER',s=>{const o=s.voies.profilePathIds.slice();s.voies.profilePathIds.reverse();if(s.profileMode==='NO_PROFILE'){s.noProfile.pathIds=s.voies.profilePathIds.slice();s.noProfile.primaryPathId=s.voies.profilePathIds[0]}return t=>{t.voies.profilePathIds=o;if(t.profileMode==='NO_PROFILE'){t.noProfile.pathIds=o.slice();t.noProfile.primaryPathId=o[0]}}}]
];
let modifications=0,aba=0;const samples=[];for(let i=0;i<1000;i++){const a=clone(legal[i%legal.length]),ra=E.computeCharacterN1(a);if(ra.errors.length)continue;let chosen=null,working,undo,rb;for(let n=0;n<ops.length;n++){const op=ops[(i+n)%ops.length];working=clone(a);undo=op[1](working);rb=E.computeCharacterN1(working);if(!rb.errors.length&&sha(mech(ra))!==sha(mech(rb))){chosen=op;break}}if(!chosen)continue;modifications++;undo(working);const back=E.computeCharacterN1(working),same=!back.errors.length&&sha(mech(ra))===sha(mech(back));if(same)aba++;if(i<40)samples.push({category:chosen[0],aLegal:true,bLegal:true,mechanicalChange:true,restored:same})}
const ghostRows=[];for(let i=0;i<200;i++){const start=clone(legal[i%legal.length]),target=clone(legal[(i*97+311)%legal.length]),working=clone(start);for(const k of ['familleId','classeId','peupleId','serieId','baseCaracs','characteristicMethod','peupleChoices','voies','equip','profileChoices','abilityChoices','advancedRules','age','history','hybrid','profileMode','noProfile','aLaCartePurchases']){if(k in target)working[k]=clone(target[k]);else delete working[k]}const tr=E.computeCharacterN1(working),fr=E.computeCharacterN1(target),same=!tr.errors.length&&!fr.errors.length&&sha(mech(tr))===sha(mech(fr));ghostRows.push({id:i,status:same?'PASS':'FAIL',transitionErrors:tr.errors,freshErrors:fr.errors})}
let saveLoad=0;for(let i=0;i<1000;i++){const d=legal[i%legal.length],r=E.computeCharacterN1(d);if(r.errors.length)continue;const p=E.createHeroSavePayload(d,r.sticky.characterState,{id:'hero-'+i,updatedAt:'2026-09-09T00:00:00Z'}),rr=E.computeCharacterN1(E.restoreHeroSavePayload(JSON.parse(JSON.stringify(p))).draft);if(!rr.errors.length&&sha(mech(r))===sha(mech(rr)))saveLoad++}
const da=legal[0],db=legal[1],ra=E.computeCharacterN1(da),rb=E.computeCharacterN1(db),pa=E.createHeroSavePayload(da,ra.sticky.characterState,{id:'hero-A'}),pb=E.createHeroSavePayload(db,rb.sticky.characterState,{id:'hero-B'}),stored=JSON.parse(JSON.stringify([pa,pb])),la=E.restoreHeroSavePayload(stored.find(x=>x.id==='hero-A')),lb=E.restoreHeroSavePayload(stored.find(x=>x.id==='hero-B')),multiHero=stored[0].id!==stored[1].id&&sha(normalizeMechanicalInput(la.draft))===sha(normalizeMechanicalInput(da))&&sha(normalizeMechanicalInput(lb.draft))===sha(normalizeMechanicalInput(db));
const meta=clone(da);meta.identite={nom:'autre'};const c1=clone(ra.sticky.characterState),c2=clone(c1);c2.identity={nom:'autre'};c2.creationInput={noise:123};const anti={fakeABARejected:sha(mech(ra))!==sha(mech(rb)),ghostLeakDetected:(()=>{const x=clone(mech(ra));x.permissions={...(x.permissions||{}),__ghost:true};return sha(x)!==sha(mech(ra))})(),wrongIllegalReasonRejected:!defs.HYBRID_NO_APPROVAL.re.test('Point-buy hors budget'),nonMechanicalModificationRejected:sha(normalizeMechanicalInput(da))===sha(normalizeMechanicalInput(meta)),metadataOnlyUniquenessRejected:sha(normalizeMechanicalCharacterState(c1))===sha(normalizeMechanicalCharacterState(c2))};anti.passed=Object.values(anti).filter(Boolean).length;anti.total=5;anti.status=anti.passed===5?'PASS':'FAIL';
const illegal={pass:rejected,total:50000,wrongReason,unexpectedAccepted:accepted,categories:Object.values(cats)};const results={finalProductSha:null,runner:'FINAL_FREEZE_TESTS/trustworthy_massive_runner.js',seed:'FOH-N1-TRUSTED-0x6f683231',startedAt,endedAt:new Date().toISOString(),LEGAL_FUZZ:legalFuzz,ILLEGAL_TARGETED:illegal,MECHANICAL_MODIFICATIONS:{pass:modifications,total:1000,registry:ops.map(x=>x[0])},MECHANICAL_A_B_A:{pass:aba,total:1000},GHOST_TRANSITIONS:ghostRows.length,GHOST_DIVERGENCES:ghostRows.filter(x=>x.status==='FAIL').length,PRODUCT_SAVE_LOAD:{pass:saveLoad,total:1000,api:'createHeroSavePayload -> JSON storage -> restoreHeroSavePayload'},MULTI_HERO_ISOLATION:multiHero?'PASS':'FAIL',ORACLE_SCENARIOS:0,ORACLE_DIVERGENCES:'NOT_TESTED',oracleStatus:'NOT_TESTED'};results.resultSha256=sha(results);
write('N1_SHA_LOCKED_MASSIVE_RESULTS.json',results);write('N1_MASSIVE_REPLAY_COVERAGE.json',{finalProductSha:null,quotas:strataResult,uniqueMechanicalInputs:uIn.size,uniqueMechanicalOutputs:uOut.size,uniqueBuildSignatures:uBuild.size,majorGaps:Object.entries(strataResult).filter(([,v])=>v.pass<v.quota).map(([k])=>k)});write('N1_ILLEGAL_REASON_PARITY.json',{finalProductSha:null,...illegal,status:rejected===50000&&wrongReason===0&&accepted===0?'PASS':'FAIL'});write('N1_MECHANICAL_MODIFICATIONS.json',{finalProductSha:null,pass:modifications,total:1000,samples});write('N1_MECHANICAL_ABA.json',{finalProductSha:null,pass:aba,total:1000,samples});write('N1_GHOST_TRANSITIONS.json',{finalProductSha:null,total:ghostRows.length,divergences:ghostRows.filter(x=>x.status==='FAIL').length,rows:ghostRows});write('N1_PRODUCT_SAVE_LOAD.json',{finalProductSha:null,pass:saveLoad,total:1000,productApi:true});write('N1_MULTI_HERO_ISOLATION.json',{finalProductSha:null,status:multiHero?'PASS':'FAIL'});write('N1_ANTI_FALSE_GREEN_PROOF.json',{finalProductSha:null,...anti});console.log(JSON.stringify({legalFuzz,illegal:{pass:rejected,wrongReason,accepted},modifications,aba,ghostDivergences:results.GHOST_DIVERGENCES,saveLoad,multiHero,anti},null,2));
