(()=>{'use strict';const api=window.BASTIDE_CHRONICLES_API,$=s=>document.querySelector(s);let entries=[],current=null;const heroes={prepotante:'Prépôtante',scanlan:'Scanlan',wilfried:'Wilfried',vivelame:'Vivelame',zepheline:'Zéphéline',faelar:'Faëlar'};const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));function toast(m){const x=$('#toast');x.textContent=m;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2600)}
function payload(){return{id:$('#entry-id').value,entry_type:$('#entry-type').value,character_id:$('#character-id').value,session_number:$('#session-number').value,session_date:$('#session-date').value,title:$('#title').value,subtitle:$('#subtitle').value,summary_text:$('#summary').value,lyrics_text:$('#lyrics').value}}
function toggleKind(){const hymn=$('#entry-type').value==='hymn';$('#character-field').hidden=!hymn;$('#session-fields').hidden=hymn;$('#title').placeholder=hymn?'L’hymne de '+(heroes[$('#character-id').value]||'ce héros'):'La ballade du naufrage glorieux';}
function preview(){const p=payload(),assets=current?.bastide_chronicle_assets||[],imgs=assets.filter(x=>x.kind==='image'),sounds=assets.filter(x=>x.kind==='audio');$('#preview').innerHTML=`<article class="scroll"><header class="scroll-head"><div><span class="session">${p.entry_type==='hymn'?'HYMNE DE '+esc((heroes[p.character_id]||'UN HÉROS').toUpperCase()):(p.session_number?'SESSION '+esc(p.session_number):'NOUVELLE CHRONIQUE')}${p.entry_type!=='hymn'&&p.session_date?' · '+esc(p.session_date):''}</span><h2>${esc(p.title||'Titre de la chronique')}</h2><p class="scroll-subtitle">${esc(p.subtitle||'Le sous-titre apparaîtra ici')}</p></div><span class="seal">S</span></header><div class="prose">${esc(p.summary_text||'Le récit prendra place sur ce parchemin.')}</div>${imgs.length?`<div class="gallery">${imgs.map(x=>`<figure><img src="${esc(x.url)}"><figcaption>${esc(x.caption)}</figcaption></figure>`).join('')}</div>`:''}${sounds.length?`<div class="songs">${sounds.map(x=>`<div class="song"><strong>♫ ${esc(x.caption||x.original_name)}</strong><audio controls preload="none" src="${esc(x.url)}"></audio></div>`).join('')}</div>`:''}${p.lyrics_text?`<details class="lyrics" open><summary>Paroles</summary><div class="prose">${esc(p.lyrics_text)}</div></details>`:''}</article>`}
function renderList(){const id=current?.id;$('#draft-list').innerHTML=entries.map(x=>`<button class="draft-button ${x.id===id?'active':''}" data-open="${x.id}"><strong>${esc(x.title)}</strong><small>${x.status==='published'?'✓ Publiée':'Brouillon'}${x.entry_type==='hymn'?' · hymne de '+esc(heroes[x.character_id]||'héros'):(x.session_number!=null?' · session '+x.session_number:'')}</small></button>`).join('')||'<p>Aucune chronique pour le moment.</p>'}
function openEntry(entry){current=entry||null;const c=entry||{};$('#entry-id').value=c.id||'';$('#entry-type').value=c.entry_type||'chronicle';$('#character-id').value=c.character_id||'';$('#session-number').value=c.session_number??'';$('#session-date').value=c.session_date||'';$('#title').value=c.title||'';$('#subtitle').value=c.subtitle||'';$('#summary').value=c.summary_text||'';$('#lyrics').value=c.lyrics_text||'';const saved=Boolean(c.id);$('#media-zone').hidden=!saved;$('#delete-entry').hidden=!saved;$('#publish').disabled=!saved||c.status==='published';$('#unpublish').disabled=!saved||c.status!=='published';toggleKind();renderMedia();renderList();preview();window.scrollTo({top:0,behavior:'smooth'})}
function renderMedia(){const assets=current?.bastide_chronicle_assets||[];$('#media-list').innerHTML=assets.map(x=>`<div class="media-row"><span>${x.kind==='audio'?'♫':'▧'} ${esc(x.caption||x.original_name)}</span><button data-delete-asset="${x.id}" type="button">Supprimer</button></div>`).join('')}
async function refresh(keep){const data=await api.request('dashboard',{editor:true});entries=data.chronicles;const chosen=entries.find(x=>x.id===(keep||current?.id));openEntry(chosen||entries[0]||null)}
async function save(e){e?.preventDefault();try{const data=await api.request('save',{method:'POST',body:payload(),editor:true});await refresh(data.id);toast('Brouillon enregistré.')}catch(err){toast(err.message)}}
async function upload(kind){if(!current)return;const input=$(kind==='audio'?'#audio-file':'#image-file'),caption=$(kind==='audio'?'#audio-caption':'#image-caption').value.trim(),files=[...input.files];if(!files.length)return toast('Choisis au moins un fichier.');for(const file of files){const form=new FormData();form.append('chronicle_id',current.id);form.append('kind',kind);form.append('caption',caption);form.append('file',file);await api.request('upload',{method:'POST',body:form,editor:true})}input.value='';await refresh(current.id);toast(files.length+' fichier(s) ajouté(s).')}
async function action(name,id=current?.id){if(!id)return;await api.request(name,{method:'POST',body:{id},editor:true});await refresh(id);toast(name==='publish'?'Chronique publiée pour les joueurs.':name==='unpublish'?'Chronique remise en brouillon.':'Modification effectuée.')}
document.addEventListener('input',e=>{if(e.target.closest('#chronicle-form')){toggleKind();preview()}});document.addEventListener('change',e=>{if(e.target.closest('#chronicle-form')){toggleKind();preview()}});document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){openEntry(entries.find(x=>x.id===b.dataset.open));return}if(b.dataset.deleteAsset&&confirm('Supprimer ce média ?')){const entryId=current?.id;await api.request('delete-asset',{method:'POST',body:{id:b.dataset.deleteAsset},editor:true});await refresh(entryId);toast('Média supprimé.');return}});$('#chronicle-form').onsubmit=save;$('#new-entry').onclick=()=>openEntry(null);$('#refresh').onclick=()=>refresh();$('#publish').onclick=()=>action('publish');$('#unpublish').onclick=()=>action('unpublish');$('#upload-image').onclick=()=>upload('image').catch(e=>toast(e.message));$('#upload-audio').onclick=()=>upload('audio').catch(e=>toast(e.message));$('#delete-entry').onclick=async()=>{if(current&&confirm('Supprimer définitivement cette chronique et tous ses médias ?')){await action('delete');await refresh();toast('Chronique supprimée.')}};
async function init(){if(!api.hasToken())return fail('Ce lien ne contient pas la clé personnelle du chroniqueur. Demande au MJ de te renvoyer ton lien.');try{await api.request('verify',{method:'POST',body:{},editor:true});$('#workspace').hidden=false;await refresh()}catch(e){fail(e.message)}}function fail(m){$('#auth-error').hidden=false;$('#auth-error').textContent=m}init();})();
